/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the aprendiz table.
 */
public class AprendizPk implements Serializable
{
	protected String tipoDocumento;

	protected String numeroDocumento;

	protected String ficha;

	protected int grupoCodigo;

	/** 
	 * This attribute represents whether the primitive attribute grupoCodigo is null.
	 */
	protected boolean grupoCodigoNull;

	/** 
	 * Sets the value of tipoDocumento
	 */
	public void setTipoDocumento(String tipoDocumento)
	{
		this.tipoDocumento = tipoDocumento;
	}

	/** 
	 * Gets the value of tipoDocumento
	 */
	public String getTipoDocumento()
	{
		return tipoDocumento;
	}

	/** 
	 * Sets the value of numeroDocumento
	 */
	public void setNumeroDocumento(String numeroDocumento)
	{
		this.numeroDocumento = numeroDocumento;
	}

	/** 
	 * Gets the value of numeroDocumento
	 */
	public String getNumeroDocumento()
	{
		return numeroDocumento;
	}

	/** 
	 * Sets the value of ficha
	 */
	public void setFicha(String ficha)
	{
		this.ficha = ficha;
	}

	/** 
	 * Gets the value of ficha
	 */
	public String getFicha()
	{
		return ficha;
	}

	/** 
	 * Sets the value of grupoCodigo
	 */
	public void setGrupoCodigo(int grupoCodigo)
	{
		this.grupoCodigo = grupoCodigo;
	}

	/** 
	 * Gets the value of grupoCodigo
	 */
	public int getGrupoCodigo()
	{
		return grupoCodigo;
	}

	/**
	 * Method 'AprendizPk'
	 * 
	 */
	public AprendizPk()
	{
	}

	/**
	 * Method 'AprendizPk'
	 * 
	 * @param tipoDocumento
	 * @param numeroDocumento
	 * @param ficha
	 * @param grupoCodigo
	 */
	public AprendizPk(final String tipoDocumento, final String numeroDocumento, final String ficha, final int grupoCodigo)
	{
		this.tipoDocumento = tipoDocumento;
		this.numeroDocumento = numeroDocumento;
		this.ficha = ficha;
		this.grupoCodigo = grupoCodigo;
	}

	/** 
	 * Sets the value of grupoCodigoNull
	 */
	public void setGrupoCodigoNull(boolean grupoCodigoNull)
	{
		this.grupoCodigoNull = grupoCodigoNull;
	}

	/** 
	 * Gets the value of grupoCodigoNull
	 */
	public boolean isGrupoCodigoNull()
	{
		return grupoCodigoNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof AprendizPk)) {
			return false;
		}
		
		final AprendizPk _cast = (AprendizPk) _other;
		if (tipoDocumento == null ? _cast.tipoDocumento != tipoDocumento : !tipoDocumento.equals( _cast.tipoDocumento )) {
			return false;
		}
		
		if (numeroDocumento == null ? _cast.numeroDocumento != numeroDocumento : !numeroDocumento.equals( _cast.numeroDocumento )) {
			return false;
		}
		
		if (ficha == null ? _cast.ficha != ficha : !ficha.equals( _cast.ficha )) {
			return false;
		}
		
		if (grupoCodigo != _cast.grupoCodigo) {
			return false;
		}
		
		if (grupoCodigoNull != _cast.grupoCodigoNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (tipoDocumento != null) {
			_hashCode = 29 * _hashCode + tipoDocumento.hashCode();
		}
		
		if (numeroDocumento != null) {
			_hashCode = 29 * _hashCode + numeroDocumento.hashCode();
		}
		
		if (ficha != null) {
			_hashCode = 29 * _hashCode + ficha.hashCode();
		}
		
		_hashCode = 29 * _hashCode + grupoCodigo;
		_hashCode = 29 * _hashCode + (grupoCodigoNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.AprendizPk: " );
		ret.append( "tipoDocumento=" + tipoDocumento );
		ret.append( ", numeroDocumento=" + numeroDocumento );
		ret.append( ", ficha=" + ficha );
		ret.append( ", grupoCodigo=" + grupoCodigo );
		return ret.toString();
	}

}
