/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import co.edu.sena.controller.dao.*;
import co.edu.sena.controller.factory.*;
import co.edu.sena.controller.dao.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Cliente implements Serializable
{
	/** 
	 * This attribute maps to the column tipo_documento in the cliente table.
	 */
	protected String tipoDocumento;

	/** 
	 * This attribute maps to the column numero_documento in the cliente table.
	 */
	protected String numeroDocumento;

	/** 
	 * This attribute maps to the column primer_nombre in the cliente table.
	 */
	protected String primerNombre;

	/** 
	 * This attribute maps to the column segundo_nombre in the cliente table.
	 */
	protected String segundoNombre;

	/** 
	 * This attribute maps to the column primer_apellido in the cliente table.
	 */
	protected String primerApellido;

	/** 
	 * This attribute maps to the column segundo_apellido in the cliente table.
	 */
	protected String segundoApellido;

	/** 
	 * This attribute maps to the column foto in the cliente table.
	 */
	protected byte[] foto;

	/**
	 * Method 'Cliente'
	 * 
	 */
	public Cliente()
	{
	}

	/**
	 * Method 'getTipoDocumento'
	 * 
	 * @return String
	 */
	public String getTipoDocumento()
	{
		return tipoDocumento;
	}

	/**
	 * Method 'setTipoDocumento'
	 * 
	 * @param tipoDocumento
	 */
	public void setTipoDocumento(String tipoDocumento)
	{
		this.tipoDocumento = tipoDocumento;
	}

	/**
	 * Method 'getNumeroDocumento'
	 * 
	 * @return String
	 */
	public String getNumeroDocumento()
	{
		return numeroDocumento;
	}

	/**
	 * Method 'setNumeroDocumento'
	 * 
	 * @param numeroDocumento
	 */
	public void setNumeroDocumento(String numeroDocumento)
	{
		this.numeroDocumento = numeroDocumento;
	}

	/**
	 * Method 'getPrimerNombre'
	 * 
	 * @return String
	 */
	public String getPrimerNombre()
	{
		return primerNombre;
	}

	/**
	 * Method 'setPrimerNombre'
	 * 
	 * @param primerNombre
	 */
	public void setPrimerNombre(String primerNombre)
	{
		this.primerNombre = primerNombre;
	}

	/**
	 * Method 'getSegundoNombre'
	 * 
	 * @return String
	 */
	public String getSegundoNombre()
	{
		return segundoNombre;
	}

	/**
	 * Method 'setSegundoNombre'
	 * 
	 * @param segundoNombre
	 */
	public void setSegundoNombre(String segundoNombre)
	{
		this.segundoNombre = segundoNombre;
	}

	/**
	 * Method 'getPrimerApellido'
	 * 
	 * @return String
	 */
	public String getPrimerApellido()
	{
		return primerApellido;
	}

	/**
	 * Method 'setPrimerApellido'
	 * 
	 * @param primerApellido
	 */
	public void setPrimerApellido(String primerApellido)
	{
		this.primerApellido = primerApellido;
	}

	/**
	 * Method 'getSegundoApellido'
	 * 
	 * @return String
	 */
	public String getSegundoApellido()
	{
		return segundoApellido;
	}

	/**
	 * Method 'setSegundoApellido'
	 * 
	 * @param segundoApellido
	 */
	public void setSegundoApellido(String segundoApellido)
	{
		this.segundoApellido = segundoApellido;
	}

	/**
	 * Method 'getFoto'
	 * 
	 * @return byte[]
	 */
	public byte[] getFoto()
	{
		return foto;
	}

	/**
	 * Method 'setFoto'
	 * 
	 * @param foto
	 */
	public void setFoto(byte[] foto)
	{
		this.foto = foto;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Cliente)) {
			return false;
		}
		
		final Cliente _cast = (Cliente) _other;
		if (tipoDocumento == null ? _cast.tipoDocumento != tipoDocumento : !tipoDocumento.equals( _cast.tipoDocumento )) {
			return false;
		}
		
		if (numeroDocumento == null ? _cast.numeroDocumento != numeroDocumento : !numeroDocumento.equals( _cast.numeroDocumento )) {
			return false;
		}
		
		if (primerNombre == null ? _cast.primerNombre != primerNombre : !primerNombre.equals( _cast.primerNombre )) {
			return false;
		}
		
		if (segundoNombre == null ? _cast.segundoNombre != segundoNombre : !segundoNombre.equals( _cast.segundoNombre )) {
			return false;
		}
		
		if (primerApellido == null ? _cast.primerApellido != primerApellido : !primerApellido.equals( _cast.primerApellido )) {
			return false;
		}
		
		if (segundoApellido == null ? _cast.segundoApellido != segundoApellido : !segundoApellido.equals( _cast.segundoApellido )) {
			return false;
		}
		
		if (foto == null ? _cast.foto != foto : !foto.equals( _cast.foto )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (tipoDocumento != null) {
			_hashCode = 29 * _hashCode + tipoDocumento.hashCode();
		}
		
		if (numeroDocumento != null) {
			_hashCode = 29 * _hashCode + numeroDocumento.hashCode();
		}
		
		if (primerNombre != null) {
			_hashCode = 29 * _hashCode + primerNombre.hashCode();
		}
		
		if (segundoNombre != null) {
			_hashCode = 29 * _hashCode + segundoNombre.hashCode();
		}
		
		if (primerApellido != null) {
			_hashCode = 29 * _hashCode + primerApellido.hashCode();
		}
		
		if (segundoApellido != null) {
			_hashCode = 29 * _hashCode + segundoApellido.hashCode();
		}
		
		if (foto != null) {
			_hashCode = 29 * _hashCode + foto.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ClientePk
	 */
	public ClientePk createPk()
	{
		return new ClientePk(tipoDocumento, numeroDocumento);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.Cliente: " );
		ret.append( "tipoDocumento=" + tipoDocumento );
		ret.append( ", numeroDocumento=" + numeroDocumento );
		ret.append( ", primerNombre=" + primerNombre );
		ret.append( ", segundoNombre=" + segundoNombre );
		ret.append( ", primerApellido=" + primerApellido );
		ret.append( ", segundoApellido=" + segundoApellido );
		ret.append( ", foto=" + foto );
		return ret.toString();
	}

}
