/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the estado_formacion table.
 */
public class EstadoFormacionPk implements Serializable
{
	protected String idEstado;

	/** 
	 * Sets the value of idEstado
	 */
	public void setIdEstado(String idEstado)
	{
		this.idEstado = idEstado;
	}

	/** 
	 * Gets the value of idEstado
	 */
	public String getIdEstado()
	{
		return idEstado;
	}

	/**
	 * Method 'EstadoFormacionPk'
	 * 
	 */
	public EstadoFormacionPk()
	{
	}

	/**
	 * Method 'EstadoFormacionPk'
	 * 
	 * @param idEstado
	 */
	public EstadoFormacionPk(final String idEstado)
	{
		this.idEstado = idEstado;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof EstadoFormacionPk)) {
			return false;
		}
		
		final EstadoFormacionPk _cast = (EstadoFormacionPk) _other;
		if (idEstado == null ? _cast.idEstado != idEstado : !idEstado.equals( _cast.idEstado )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idEstado != null) {
			_hashCode = 29 * _hashCode + idEstado.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.EstadoFormacionPk: " );
		ret.append( "idEstado=" + idEstado );
		return ret.toString();
	}

}
