/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import co.edu.sena.controller.dao.*;
import co.edu.sena.controller.factory.*;
import co.edu.sena.controller.dao.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class EstadoFormacion implements Serializable
{
	/** 
	 * This attribute maps to the column id_estado in the estado_formacion table.
	 */
	protected String idEstado;

	/** 
	 * This attribute maps to the column estado in the estado_formacion table.
	 */
	protected short estado;

	/**
	 * Method 'EstadoFormacion'
	 * 
	 */
	public EstadoFormacion()
	{
	}

	/**
	 * Method 'getIdEstado'
	 * 
	 * @return String
	 */
	public String getIdEstado()
	{
		return idEstado;
	}

	/**
	 * Method 'setIdEstado'
	 * 
	 * @param idEstado
	 */
	public void setIdEstado(String idEstado)
	{
		this.idEstado = idEstado;
	}

	/**
	 * Method 'getEstado'
	 * 
	 * @return short
	 */
	public short getEstado()
	{
		return estado;
	}

	/**
	 * Method 'setEstado'
	 * 
	 * @param estado
	 */
	public void setEstado(short estado)
	{
		this.estado = estado;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof EstadoFormacion)) {
			return false;
		}
		
		final EstadoFormacion _cast = (EstadoFormacion) _other;
		if (idEstado == null ? _cast.idEstado != idEstado : !idEstado.equals( _cast.idEstado )) {
			return false;
		}
		
		if (estado != _cast.estado) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idEstado != null) {
			_hashCode = 29 * _hashCode + idEstado.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) estado;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return EstadoFormacionPk
	 */
	public EstadoFormacionPk createPk()
	{
		return new EstadoFormacionPk(idEstado);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.EstadoFormacion: " );
		ret.append( "idEstado=" + idEstado );
		ret.append( ", estado=" + estado );
		return ret.toString();
	}

}
