/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the ficha_has_lista table.
 */
public class FichaHasListaPk implements Serializable
{
	protected String ficha;

	/** 
	 * Sets the value of ficha
	 */
	public void setFicha(String ficha)
	{
		this.ficha = ficha;
	}

	/** 
	 * Gets the value of ficha
	 */
	public String getFicha()
	{
		return ficha;
	}

	/**
	 * Method 'FichaHasListaPk'
	 * 
	 */
	public FichaHasListaPk()
	{
	}

	/**
	 * Method 'FichaHasListaPk'
	 * 
	 * @param ficha
	 */
	public FichaHasListaPk(final String ficha)
	{
		this.ficha = ficha;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof FichaHasListaPk)) {
			return false;
		}
		
		final FichaHasListaPk _cast = (FichaHasListaPk) _other;
		if (ficha == null ? _cast.ficha != ficha : !ficha.equals( _cast.ficha )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (ficha != null) {
			_hashCode = 29 * _hashCode + ficha.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.FichaHasListaPk: " );
		ret.append( "ficha=" + ficha );
		return ret.toString();
	}

}
