/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import co.edu.sena.controller.dao.*;
import co.edu.sena.controller.factory.*;
import co.edu.sena.controller.dao.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class GrupoProyecto implements Serializable
{
	/** 
	 * This attribute maps to the column numero_ficha in the grupo_proyecto table.
	 */
	protected String numeroFicha;

	/** 
	 * This attribute maps to the column codigo in the grupo_proyecto table.
	 */
	protected int codigo;

	/** 
	 * This attribute maps to the column nombre_proyecto in the grupo_proyecto table.
	 */
	protected String nombreProyecto;

	/** 
	 * This attribute maps to the column estado_grupo in the grupo_proyecto table.
	 */
	protected String estadoGrupo;

	/**
	 * Method 'GrupoProyecto'
	 * 
	 */
	public GrupoProyecto()
	{
	}

	/**
	 * Method 'getNumeroFicha'
	 * 
	 * @return String
	 */
	public String getNumeroFicha()
	{
		return numeroFicha;
	}

	/**
	 * Method 'setNumeroFicha'
	 * 
	 * @param numeroFicha
	 */
	public void setNumeroFicha(String numeroFicha)
	{
		this.numeroFicha = numeroFicha;
	}

	/**
	 * Method 'getCodigo'
	 * 
	 * @return int
	 */
	public int getCodigo()
	{
		return codigo;
	}

	/**
	 * Method 'setCodigo'
	 * 
	 * @param codigo
	 */
	public void setCodigo(int codigo)
	{
		this.codigo = codigo;
	}

	/**
	 * Method 'getNombreProyecto'
	 * 
	 * @return String
	 */
	public String getNombreProyecto()
	{
		return nombreProyecto;
	}

	/**
	 * Method 'setNombreProyecto'
	 * 
	 * @param nombreProyecto
	 */
	public void setNombreProyecto(String nombreProyecto)
	{
		this.nombreProyecto = nombreProyecto;
	}

	/**
	 * Method 'getEstadoGrupo'
	 * 
	 * @return String
	 */
	public String getEstadoGrupo()
	{
		return estadoGrupo;
	}

	/**
	 * Method 'setEstadoGrupo'
	 * 
	 * @param estadoGrupo
	 */
	public void setEstadoGrupo(String estadoGrupo)
	{
		this.estadoGrupo = estadoGrupo;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof GrupoProyecto)) {
			return false;
		}
		
		final GrupoProyecto _cast = (GrupoProyecto) _other;
		if (numeroFicha == null ? _cast.numeroFicha != numeroFicha : !numeroFicha.equals( _cast.numeroFicha )) {
			return false;
		}
		
		if (codigo != _cast.codigo) {
			return false;
		}
		
		if (nombreProyecto == null ? _cast.nombreProyecto != nombreProyecto : !nombreProyecto.equals( _cast.nombreProyecto )) {
			return false;
		}
		
		if (estadoGrupo == null ? _cast.estadoGrupo != estadoGrupo : !estadoGrupo.equals( _cast.estadoGrupo )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (numeroFicha != null) {
			_hashCode = 29 * _hashCode + numeroFicha.hashCode();
		}
		
		_hashCode = 29 * _hashCode + codigo;
		if (nombreProyecto != null) {
			_hashCode = 29 * _hashCode + nombreProyecto.hashCode();
		}
		
		if (estadoGrupo != null) {
			_hashCode = 29 * _hashCode + estadoGrupo.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return GrupoProyectoPk
	 */
	public GrupoProyectoPk createPk()
	{
		return new GrupoProyectoPk(numeroFicha, codigo);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.GrupoProyecto: " );
		ret.append( "numeroFicha=" + numeroFicha );
		ret.append( ", codigo=" + codigo );
		ret.append( ", nombreProyecto=" + nombreProyecto );
		ret.append( ", estadoGrupo=" + estadoGrupo );
		return ret.toString();
	}

}
