/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the grupo_proyecto table.
 */
public class GrupoProyectoPk implements Serializable
{
	protected String numeroFicha;

	protected int codigo;

	/** 
	 * This attribute represents whether the primitive attribute codigo is null.
	 */
	protected boolean codigoNull;

	/** 
	 * Sets the value of numeroFicha
	 */
	public void setNumeroFicha(String numeroFicha)
	{
		this.numeroFicha = numeroFicha;
	}

	/** 
	 * Gets the value of numeroFicha
	 */
	public String getNumeroFicha()
	{
		return numeroFicha;
	}

	/** 
	 * Sets the value of codigo
	 */
	public void setCodigo(int codigo)
	{
		this.codigo = codigo;
	}

	/** 
	 * Gets the value of codigo
	 */
	public int getCodigo()
	{
		return codigo;
	}

	/**
	 * Method 'GrupoProyectoPk'
	 * 
	 */
	public GrupoProyectoPk()
	{
	}

	/**
	 * Method 'GrupoProyectoPk'
	 * 
	 * @param numeroFicha
	 * @param codigo
	 */
	public GrupoProyectoPk(final String numeroFicha, final int codigo)
	{
		this.numeroFicha = numeroFicha;
		this.codigo = codigo;
	}

	/** 
	 * Sets the value of codigoNull
	 */
	public void setCodigoNull(boolean codigoNull)
	{
		this.codigoNull = codigoNull;
	}

	/** 
	 * Gets the value of codigoNull
	 */
	public boolean isCodigoNull()
	{
		return codigoNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof GrupoProyectoPk)) {
			return false;
		}
		
		final GrupoProyectoPk _cast = (GrupoProyectoPk) _other;
		if (numeroFicha == null ? _cast.numeroFicha != numeroFicha : !numeroFicha.equals( _cast.numeroFicha )) {
			return false;
		}
		
		if (codigo != _cast.codigo) {
			return false;
		}
		
		if (codigoNull != _cast.codigoNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (numeroFicha != null) {
			_hashCode = 29 * _hashCode + numeroFicha.hashCode();
		}
		
		_hashCode = 29 * _hashCode + codigo;
		_hashCode = 29 * _hashCode + (codigoNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.GrupoProyectoPk: " );
		ret.append( "numeroFicha=" + numeroFicha );
		ret.append( ", codigo=" + codigo );
		return ret.toString();
	}

}
