/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the instructor_has_trimestre table.
 */
public class InstructorHasTrimestrePk implements Serializable
{
	protected String tipoDocumento;

	protected String numeroDocumento;

	protected String ficha;

	protected String idTrimestre;

	protected String jornada;

	protected String tipoInstructor;

	/** 
	 * Sets the value of tipoDocumento
	 */
	public void setTipoDocumento(String tipoDocumento)
	{
		this.tipoDocumento = tipoDocumento;
	}

	/** 
	 * Gets the value of tipoDocumento
	 */
	public String getTipoDocumento()
	{
		return tipoDocumento;
	}

	/** 
	 * Sets the value of numeroDocumento
	 */
	public void setNumeroDocumento(String numeroDocumento)
	{
		this.numeroDocumento = numeroDocumento;
	}

	/** 
	 * Gets the value of numeroDocumento
	 */
	public String getNumeroDocumento()
	{
		return numeroDocumento;
	}

	/** 
	 * Sets the value of ficha
	 */
	public void setFicha(String ficha)
	{
		this.ficha = ficha;
	}

	/** 
	 * Gets the value of ficha
	 */
	public String getFicha()
	{
		return ficha;
	}

	/** 
	 * Sets the value of idTrimestre
	 */
	public void setIdTrimestre(String idTrimestre)
	{
		this.idTrimestre = idTrimestre;
	}

	/** 
	 * Gets the value of idTrimestre
	 */
	public String getIdTrimestre()
	{
		return idTrimestre;
	}

	/** 
	 * Sets the value of jornada
	 */
	public void setJornada(String jornada)
	{
		this.jornada = jornada;
	}

	/** 
	 * Gets the value of jornada
	 */
	public String getJornada()
	{
		return jornada;
	}

	/** 
	 * Sets the value of tipoInstructor
	 */
	public void setTipoInstructor(String tipoInstructor)
	{
		this.tipoInstructor = tipoInstructor;
	}

	/** 
	 * Gets the value of tipoInstructor
	 */
	public String getTipoInstructor()
	{
		return tipoInstructor;
	}

	/**
	 * Method 'InstructorHasTrimestrePk'
	 * 
	 */
	public InstructorHasTrimestrePk()
	{
	}

	/**
	 * Method 'InstructorHasTrimestrePk'
	 * 
	 * @param tipoDocumento
	 * @param numeroDocumento
	 * @param ficha
	 * @param idTrimestre
	 * @param jornada
	 * @param tipoInstructor
	 */
	public InstructorHasTrimestrePk(final String tipoDocumento, final String numeroDocumento, final String ficha, final String idTrimestre, final String jornada, final String tipoInstructor)
	{
		this.tipoDocumento = tipoDocumento;
		this.numeroDocumento = numeroDocumento;
		this.ficha = ficha;
		this.idTrimestre = idTrimestre;
		this.jornada = jornada;
		this.tipoInstructor = tipoInstructor;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof InstructorHasTrimestrePk)) {
			return false;
		}
		
		final InstructorHasTrimestrePk _cast = (InstructorHasTrimestrePk) _other;
		if (tipoDocumento == null ? _cast.tipoDocumento != tipoDocumento : !tipoDocumento.equals( _cast.tipoDocumento )) {
			return false;
		}
		
		if (numeroDocumento == null ? _cast.numeroDocumento != numeroDocumento : !numeroDocumento.equals( _cast.numeroDocumento )) {
			return false;
		}
		
		if (ficha == null ? _cast.ficha != ficha : !ficha.equals( _cast.ficha )) {
			return false;
		}
		
		if (idTrimestre == null ? _cast.idTrimestre != idTrimestre : !idTrimestre.equals( _cast.idTrimestre )) {
			return false;
		}
		
		if (jornada == null ? _cast.jornada != jornada : !jornada.equals( _cast.jornada )) {
			return false;
		}
		
		if (tipoInstructor == null ? _cast.tipoInstructor != tipoInstructor : !tipoInstructor.equals( _cast.tipoInstructor )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (tipoDocumento != null) {
			_hashCode = 29 * _hashCode + tipoDocumento.hashCode();
		}
		
		if (numeroDocumento != null) {
			_hashCode = 29 * _hashCode + numeroDocumento.hashCode();
		}
		
		if (ficha != null) {
			_hashCode = 29 * _hashCode + ficha.hashCode();
		}
		
		if (idTrimestre != null) {
			_hashCode = 29 * _hashCode + idTrimestre.hashCode();
		}
		
		if (jornada != null) {
			_hashCode = 29 * _hashCode + jornada.hashCode();
		}
		
		if (tipoInstructor != null) {
			_hashCode = 29 * _hashCode + tipoInstructor.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.InstructorHasTrimestrePk: " );
		ret.append( "tipoDocumento=" + tipoDocumento );
		ret.append( ", numeroDocumento=" + numeroDocumento );
		ret.append( ", ficha=" + ficha );
		ret.append( ", idTrimestre=" + idTrimestre );
		ret.append( ", jornada=" + jornada );
		ret.append( ", tipoInstructor=" + tipoInstructor );
		return ret.toString();
	}

}
