/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import co.edu.sena.controller.dao.*;
import co.edu.sena.controller.factory.*;
import co.edu.sena.controller.dao.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class InstructorHasTrimestre implements Serializable
{
	/** 
	 * This attribute maps to the column tipo_documento in the instructor_has_trimestre table.
	 */
	protected String tipoDocumento;

	/** 
	 * This attribute maps to the column numero_documento in the instructor_has_trimestre table.
	 */
	protected String numeroDocumento;

	/** 
	 * This attribute maps to the column ficha in the instructor_has_trimestre table.
	 */
	protected String ficha;

	/** 
	 * This attribute maps to the column id_trimestre in the instructor_has_trimestre table.
	 */
	protected String idTrimestre;

	/** 
	 * This attribute maps to the column jornada in the instructor_has_trimestre table.
	 */
	protected String jornada;

	/** 
	 * This attribute maps to the column tipo_instructor in the instructor_has_trimestre table.
	 */
	protected String tipoInstructor;

	/**
	 * Method 'InstructorHasTrimestre'
	 * 
	 */
	public InstructorHasTrimestre()
	{
	}

	/**
	 * Method 'getTipoDocumento'
	 * 
	 * @return String
	 */
	public String getTipoDocumento()
	{
		return tipoDocumento;
	}

	/**
	 * Method 'setTipoDocumento'
	 * 
	 * @param tipoDocumento
	 */
	public void setTipoDocumento(String tipoDocumento)
	{
		this.tipoDocumento = tipoDocumento;
	}

	/**
	 * Method 'getNumeroDocumento'
	 * 
	 * @return String
	 */
	public String getNumeroDocumento()
	{
		return numeroDocumento;
	}

	/**
	 * Method 'setNumeroDocumento'
	 * 
	 * @param numeroDocumento
	 */
	public void setNumeroDocumento(String numeroDocumento)
	{
		this.numeroDocumento = numeroDocumento;
	}

	/**
	 * Method 'getFicha'
	 * 
	 * @return String
	 */
	public String getFicha()
	{
		return ficha;
	}

	/**
	 * Method 'setFicha'
	 * 
	 * @param ficha
	 */
	public void setFicha(String ficha)
	{
		this.ficha = ficha;
	}

	/**
	 * Method 'getIdTrimestre'
	 * 
	 * @return String
	 */
	public String getIdTrimestre()
	{
		return idTrimestre;
	}

	/**
	 * Method 'setIdTrimestre'
	 * 
	 * @param idTrimestre
	 */
	public void setIdTrimestre(String idTrimestre)
	{
		this.idTrimestre = idTrimestre;
	}

	/**
	 * Method 'getJornada'
	 * 
	 * @return String
	 */
	public String getJornada()
	{
		return jornada;
	}

	/**
	 * Method 'setJornada'
	 * 
	 * @param jornada
	 */
	public void setJornada(String jornada)
	{
		this.jornada = jornada;
	}

	/**
	 * Method 'getTipoInstructor'
	 * 
	 * @return String
	 */
	public String getTipoInstructor()
	{
		return tipoInstructor;
	}

	/**
	 * Method 'setTipoInstructor'
	 * 
	 * @param tipoInstructor
	 */
	public void setTipoInstructor(String tipoInstructor)
	{
		this.tipoInstructor = tipoInstructor;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof InstructorHasTrimestre)) {
			return false;
		}
		
		final InstructorHasTrimestre _cast = (InstructorHasTrimestre) _other;
		if (tipoDocumento == null ? _cast.tipoDocumento != tipoDocumento : !tipoDocumento.equals( _cast.tipoDocumento )) {
			return false;
		}
		
		if (numeroDocumento == null ? _cast.numeroDocumento != numeroDocumento : !numeroDocumento.equals( _cast.numeroDocumento )) {
			return false;
		}
		
		if (ficha == null ? _cast.ficha != ficha : !ficha.equals( _cast.ficha )) {
			return false;
		}
		
		if (idTrimestre == null ? _cast.idTrimestre != idTrimestre : !idTrimestre.equals( _cast.idTrimestre )) {
			return false;
		}
		
		if (jornada == null ? _cast.jornada != jornada : !jornada.equals( _cast.jornada )) {
			return false;
		}
		
		if (tipoInstructor == null ? _cast.tipoInstructor != tipoInstructor : !tipoInstructor.equals( _cast.tipoInstructor )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (tipoDocumento != null) {
			_hashCode = 29 * _hashCode + tipoDocumento.hashCode();
		}
		
		if (numeroDocumento != null) {
			_hashCode = 29 * _hashCode + numeroDocumento.hashCode();
		}
		
		if (ficha != null) {
			_hashCode = 29 * _hashCode + ficha.hashCode();
		}
		
		if (idTrimestre != null) {
			_hashCode = 29 * _hashCode + idTrimestre.hashCode();
		}
		
		if (jornada != null) {
			_hashCode = 29 * _hashCode + jornada.hashCode();
		}
		
		if (tipoInstructor != null) {
			_hashCode = 29 * _hashCode + tipoInstructor.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return InstructorHasTrimestrePk
	 */
	public InstructorHasTrimestrePk createPk()
	{
		return new InstructorHasTrimestrePk(tipoDocumento, numeroDocumento, ficha, idTrimestre, jornada, tipoInstructor);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.InstructorHasTrimestre: " );
		ret.append( "tipoDocumento=" + tipoDocumento );
		ret.append( ", numeroDocumento=" + numeroDocumento );
		ret.append( ", ficha=" + ficha );
		ret.append( ", idTrimestre=" + idTrimestre );
		ret.append( ", jornada=" + jornada );
		ret.append( ", tipoInstructor=" + tipoInstructor );
		return ret.toString();
	}

}
