/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import co.edu.sena.controller.dao.*;
import co.edu.sena.controller.factory.*;
import co.edu.sena.controller.dao.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class ItemChecker implements Serializable
{
	/** 
	 * This attribute maps to the column lista_chequeo in the item_checker table.
	 */
	protected String listaChequeo;

	/** 
	 * This attribute maps to the column id_item in the item_checker table.
	 */
	protected int idItem;

	/** 
	 * This attribute maps to the column pregunta in the item_checker table.
	 */
	protected String pregunta;

	/** 
	 * This attribute maps to the column rae_codigo in the item_checker table.
	 */
	protected String raeCodigo;

	/** 
	 * This attribute maps to the column competencia_codigo in the item_checker table.
	 */
	protected String competenciaCodigo;

	/** 
	 * This attribute maps to the column programa_codigo_version in the item_checker table.
	 */
	protected String programaCodigoVersion;

	/**
	 * Method 'ItemChecker'
	 * 
	 */
	public ItemChecker()
	{
	}

	/**
	 * Method 'getListaChequeo'
	 * 
	 * @return String
	 */
	public String getListaChequeo()
	{
		return listaChequeo;
	}

	/**
	 * Method 'setListaChequeo'
	 * 
	 * @param listaChequeo
	 */
	public void setListaChequeo(String listaChequeo)
	{
		this.listaChequeo = listaChequeo;
	}

	/**
	 * Method 'getIdItem'
	 * 
	 * @return int
	 */
	public int getIdItem()
	{
		return idItem;
	}

	/**
	 * Method 'setIdItem'
	 * 
	 * @param idItem
	 */
	public void setIdItem(int idItem)
	{
		this.idItem = idItem;
	}

	/**
	 * Method 'getPregunta'
	 * 
	 * @return String
	 */
	public String getPregunta()
	{
		return pregunta;
	}

	/**
	 * Method 'setPregunta'
	 * 
	 * @param pregunta
	 */
	public void setPregunta(String pregunta)
	{
		this.pregunta = pregunta;
	}

	/**
	 * Method 'getRaeCodigo'
	 * 
	 * @return String
	 */
	public String getRaeCodigo()
	{
		return raeCodigo;
	}

	/**
	 * Method 'setRaeCodigo'
	 * 
	 * @param raeCodigo
	 */
	public void setRaeCodigo(String raeCodigo)
	{
		this.raeCodigo = raeCodigo;
	}

	/**
	 * Method 'getCompetenciaCodigo'
	 * 
	 * @return String
	 */
	public String getCompetenciaCodigo()
	{
		return competenciaCodigo;
	}

	/**
	 * Method 'setCompetenciaCodigo'
	 * 
	 * @param competenciaCodigo
	 */
	public void setCompetenciaCodigo(String competenciaCodigo)
	{
		this.competenciaCodigo = competenciaCodigo;
	}

	/**
	 * Method 'getProgramaCodigoVersion'
	 * 
	 * @return String
	 */
	public String getProgramaCodigoVersion()
	{
		return programaCodigoVersion;
	}

	/**
	 * Method 'setProgramaCodigoVersion'
	 * 
	 * @param programaCodigoVersion
	 */
	public void setProgramaCodigoVersion(String programaCodigoVersion)
	{
		this.programaCodigoVersion = programaCodigoVersion;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ItemChecker)) {
			return false;
		}
		
		final ItemChecker _cast = (ItemChecker) _other;
		if (listaChequeo == null ? _cast.listaChequeo != listaChequeo : !listaChequeo.equals( _cast.listaChequeo )) {
			return false;
		}
		
		if (idItem != _cast.idItem) {
			return false;
		}
		
		if (pregunta == null ? _cast.pregunta != pregunta : !pregunta.equals( _cast.pregunta )) {
			return false;
		}
		
		if (raeCodigo == null ? _cast.raeCodigo != raeCodigo : !raeCodigo.equals( _cast.raeCodigo )) {
			return false;
		}
		
		if (competenciaCodigo == null ? _cast.competenciaCodigo != competenciaCodigo : !competenciaCodigo.equals( _cast.competenciaCodigo )) {
			return false;
		}
		
		if (programaCodigoVersion == null ? _cast.programaCodigoVersion != programaCodigoVersion : !programaCodigoVersion.equals( _cast.programaCodigoVersion )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (listaChequeo != null) {
			_hashCode = 29 * _hashCode + listaChequeo.hashCode();
		}
		
		_hashCode = 29 * _hashCode + idItem;
		if (pregunta != null) {
			_hashCode = 29 * _hashCode + pregunta.hashCode();
		}
		
		if (raeCodigo != null) {
			_hashCode = 29 * _hashCode + raeCodigo.hashCode();
		}
		
		if (competenciaCodigo != null) {
			_hashCode = 29 * _hashCode + competenciaCodigo.hashCode();
		}
		
		if (programaCodigoVersion != null) {
			_hashCode = 29 * _hashCode + programaCodigoVersion.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ItemCheckerPk
	 */
	public ItemCheckerPk createPk()
	{
		return new ItemCheckerPk(listaChequeo, idItem);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.ItemChecker: " );
		ret.append( "listaChequeo=" + listaChequeo );
		ret.append( ", idItem=" + idItem );
		ret.append( ", pregunta=" + pregunta );
		ret.append( ", raeCodigo=" + raeCodigo );
		ret.append( ", competenciaCodigo=" + competenciaCodigo );
		ret.append( ", programaCodigoVersion=" + programaCodigoVersion );
		return ret.toString();
	}

}
