/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the lista_chequeo table.
 */
public class ListaChequeoPk implements Serializable
{
	protected String idLista;

	/** 
	 * Sets the value of idLista
	 */
	public void setIdLista(String idLista)
	{
		this.idLista = idLista;
	}

	/** 
	 * Gets the value of idLista
	 */
	public String getIdLista()
	{
		return idLista;
	}

	/**
	 * Method 'ListaChequeoPk'
	 * 
	 */
	public ListaChequeoPk()
	{
	}

	/**
	 * Method 'ListaChequeoPk'
	 * 
	 * @param idLista
	 */
	public ListaChequeoPk(final String idLista)
	{
		this.idLista = idLista;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ListaChequeoPk)) {
			return false;
		}
		
		final ListaChequeoPk _cast = (ListaChequeoPk) _other;
		if (idLista == null ? _cast.idLista != idLista : !idLista.equals( _cast.idLista )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idLista != null) {
			_hashCode = 29 * _hashCode + idLista.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.ListaChequeoPk: " );
		ret.append( "idLista=" + idLista );
		return ret.toString();
	}

}
