/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import co.edu.sena.controller.dao.*;
import co.edu.sena.controller.factory.*;
import co.edu.sena.controller.dao.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class ListaChequeo implements Serializable
{
	/** 
	 * This attribute maps to the column id_lista in the lista_chequeo table.
	 */
	protected String idLista;

	/** 
	 * This attribute maps to the column estado in the lista_chequeo table.
	 */
	protected short estado;

	/** 
	 * This attribute maps to the column programa_codigo_version in the lista_chequeo table.
	 */
	protected String programaCodigoVersion;

	/**
	 * Method 'ListaChequeo'
	 * 
	 */
	public ListaChequeo()
	{
	}

	/**
	 * Method 'getIdLista'
	 * 
	 * @return String
	 */
	public String getIdLista()
	{
		return idLista;
	}

	/**
	 * Method 'setIdLista'
	 * 
	 * @param idLista
	 */
	public void setIdLista(String idLista)
	{
		this.idLista = idLista;
	}

	/**
	 * Method 'getEstado'
	 * 
	 * @return short
	 */
	public short getEstado()
	{
		return estado;
	}

	/**
	 * Method 'setEstado'
	 * 
	 * @param estado
	 */
	public void setEstado(short estado)
	{
		this.estado = estado;
	}

	/**
	 * Method 'getProgramaCodigoVersion'
	 * 
	 * @return String
	 */
	public String getProgramaCodigoVersion()
	{
		return programaCodigoVersion;
	}

	/**
	 * Method 'setProgramaCodigoVersion'
	 * 
	 * @param programaCodigoVersion
	 */
	public void setProgramaCodigoVersion(String programaCodigoVersion)
	{
		this.programaCodigoVersion = programaCodigoVersion;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ListaChequeo)) {
			return false;
		}
		
		final ListaChequeo _cast = (ListaChequeo) _other;
		if (idLista == null ? _cast.idLista != idLista : !idLista.equals( _cast.idLista )) {
			return false;
		}
		
		if (estado != _cast.estado) {
			return false;
		}
		
		if (programaCodigoVersion == null ? _cast.programaCodigoVersion != programaCodigoVersion : !programaCodigoVersion.equals( _cast.programaCodigoVersion )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idLista != null) {
			_hashCode = 29 * _hashCode + idLista.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) estado;
		if (programaCodigoVersion != null) {
			_hashCode = 29 * _hashCode + programaCodigoVersion.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ListaChequeoPk
	 */
	public ListaChequeoPk createPk()
	{
		return new ListaChequeoPk(idLista);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.ListaChequeo: " );
		ret.append( "idLista=" + idLista );
		ret.append( ", estado=" + estado );
		ret.append( ", programaCodigoVersion=" + programaCodigoVersion );
		return ret.toString();
	}

}
