/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import co.edu.sena.controller.dao.*;
import co.edu.sena.controller.factory.*;
import co.edu.sena.controller.dao.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class ObservacionItem implements Serializable
{
	/** 
	 * This attribute maps to the column id_observacion in the observacion_item table.
	 */
	protected int idObservacion;

	/** 
	 * This attribute maps to the column numero_ficha in the observacion_item table.
	 */
	protected String numeroFicha;

	/** 
	 * This attribute maps to the column grupo_codigo in the observacion_item table.
	 */
	protected int grupoCodigo;

	/** 
	 * This attribute maps to the column lista_chequeo in the observacion_item table.
	 */
	protected String listaChequeo;

	/** 
	 * This attribute maps to the column id_item in the observacion_item table.
	 */
	protected int idItem;

	/** 
	 * This attribute maps to the column observacion in the observacion_item table.
	 */
	protected String observacion;

	/** 
	 * This attribute maps to the column jurados in the observacion_item table.
	 */
	protected String jurados;

	/** 
	 * This attribute maps to the column fecha in the observacion_item table.
	 */
	protected Date fecha;

	/** 
	 * This attribute maps to the column usuario in the observacion_item table.
	 */
	protected String usuario;

	/**
	 * Method 'ObservacionItem'
	 * 
	 */
	public ObservacionItem()
	{
	}

	/**
	 * Method 'getIdObservacion'
	 * 
	 * @return int
	 */
	public int getIdObservacion()
	{
		return idObservacion;
	}

	/**
	 * Method 'setIdObservacion'
	 * 
	 * @param idObservacion
	 */
	public void setIdObservacion(int idObservacion)
	{
		this.idObservacion = idObservacion;
	}

	/**
	 * Method 'getNumeroFicha'
	 * 
	 * @return String
	 */
	public String getNumeroFicha()
	{
		return numeroFicha;
	}

	/**
	 * Method 'setNumeroFicha'
	 * 
	 * @param numeroFicha
	 */
	public void setNumeroFicha(String numeroFicha)
	{
		this.numeroFicha = numeroFicha;
	}

	/**
	 * Method 'getGrupoCodigo'
	 * 
	 * @return int
	 */
	public int getGrupoCodigo()
	{
		return grupoCodigo;
	}

	/**
	 * Method 'setGrupoCodigo'
	 * 
	 * @param grupoCodigo
	 */
	public void setGrupoCodigo(int grupoCodigo)
	{
		this.grupoCodigo = grupoCodigo;
	}

	/**
	 * Method 'getListaChequeo'
	 * 
	 * @return String
	 */
	public String getListaChequeo()
	{
		return listaChequeo;
	}

	/**
	 * Method 'setListaChequeo'
	 * 
	 * @param listaChequeo
	 */
	public void setListaChequeo(String listaChequeo)
	{
		this.listaChequeo = listaChequeo;
	}

	/**
	 * Method 'getIdItem'
	 * 
	 * @return int
	 */
	public int getIdItem()
	{
		return idItem;
	}

	/**
	 * Method 'setIdItem'
	 * 
	 * @param idItem
	 */
	public void setIdItem(int idItem)
	{
		this.idItem = idItem;
	}

	/**
	 * Method 'getObservacion'
	 * 
	 * @return String
	 */
	public String getObservacion()
	{
		return observacion;
	}

	/**
	 * Method 'setObservacion'
	 * 
	 * @param observacion
	 */
	public void setObservacion(String observacion)
	{
		this.observacion = observacion;
	}

	/**
	 * Method 'getJurados'
	 * 
	 * @return String
	 */
	public String getJurados()
	{
		return jurados;
	}

	/**
	 * Method 'setJurados'
	 * 
	 * @param jurados
	 */
	public void setJurados(String jurados)
	{
		this.jurados = jurados;
	}

	/**
	 * Method 'getFecha'
	 * 
	 * @return Date
	 */
	public Date getFecha()
	{
		return fecha;
	}

	/**
	 * Method 'setFecha'
	 * 
	 * @param fecha
	 */
	public void setFecha(Date fecha)
	{
		this.fecha = fecha;
	}

	/**
	 * Method 'getUsuario'
	 * 
	 * @return String
	 */
	public String getUsuario()
	{
		return usuario;
	}

	/**
	 * Method 'setUsuario'
	 * 
	 * @param usuario
	 */
	public void setUsuario(String usuario)
	{
		this.usuario = usuario;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ObservacionItem)) {
			return false;
		}
		
		final ObservacionItem _cast = (ObservacionItem) _other;
		if (idObservacion != _cast.idObservacion) {
			return false;
		}
		
		if (numeroFicha == null ? _cast.numeroFicha != numeroFicha : !numeroFicha.equals( _cast.numeroFicha )) {
			return false;
		}
		
		if (grupoCodigo != _cast.grupoCodigo) {
			return false;
		}
		
		if (listaChequeo == null ? _cast.listaChequeo != listaChequeo : !listaChequeo.equals( _cast.listaChequeo )) {
			return false;
		}
		
		if (idItem != _cast.idItem) {
			return false;
		}
		
		if (observacion == null ? _cast.observacion != observacion : !observacion.equals( _cast.observacion )) {
			return false;
		}
		
		if (jurados == null ? _cast.jurados != jurados : !jurados.equals( _cast.jurados )) {
			return false;
		}
		
		if (fecha == null ? _cast.fecha != fecha : !fecha.equals( _cast.fecha )) {
			return false;
		}
		
		if (usuario == null ? _cast.usuario != usuario : !usuario.equals( _cast.usuario )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idObservacion;
		if (numeroFicha != null) {
			_hashCode = 29 * _hashCode + numeroFicha.hashCode();
		}
		
		_hashCode = 29 * _hashCode + grupoCodigo;
		if (listaChequeo != null) {
			_hashCode = 29 * _hashCode + listaChequeo.hashCode();
		}
		
		_hashCode = 29 * _hashCode + idItem;
		if (observacion != null) {
			_hashCode = 29 * _hashCode + observacion.hashCode();
		}
		
		if (jurados != null) {
			_hashCode = 29 * _hashCode + jurados.hashCode();
		}
		
		if (fecha != null) {
			_hashCode = 29 * _hashCode + fecha.hashCode();
		}
		
		if (usuario != null) {
			_hashCode = 29 * _hashCode + usuario.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ObservacionItemPk
	 */
	public ObservacionItemPk createPk()
	{
		return new ObservacionItemPk(idObservacion, numeroFicha, grupoCodigo, listaChequeo, idItem);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.ObservacionItem: " );
		ret.append( "idObservacion=" + idObservacion );
		ret.append( ", numeroFicha=" + numeroFicha );
		ret.append( ", grupoCodigo=" + grupoCodigo );
		ret.append( ", listaChequeo=" + listaChequeo );
		ret.append( ", idItem=" + idItem );
		ret.append( ", observacion=" + observacion );
		ret.append( ", jurados=" + jurados );
		ret.append( ", fecha=" + fecha );
		ret.append( ", usuario=" + usuario );
		return ret.toString();
	}

}
