/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the observacion_general table.
 */
public class ObservacionGeneralPk implements Serializable
{
	protected String grupoNumeroFicha;

	protected int grupoCodigo;

	protected int idObservacion;

	/** 
	 * This attribute represents whether the primitive attribute grupoCodigo is null.
	 */
	protected boolean grupoCodigoNull;

	/** 
	 * This attribute represents whether the primitive attribute idObservacion is null.
	 */
	protected boolean idObservacionNull;

	/** 
	 * Sets the value of grupoNumeroFicha
	 */
	public void setGrupoNumeroFicha(String grupoNumeroFicha)
	{
		this.grupoNumeroFicha = grupoNumeroFicha;
	}

	/** 
	 * Gets the value of grupoNumeroFicha
	 */
	public String getGrupoNumeroFicha()
	{
		return grupoNumeroFicha;
	}

	/** 
	 * Sets the value of grupoCodigo
	 */
	public void setGrupoCodigo(int grupoCodigo)
	{
		this.grupoCodigo = grupoCodigo;
	}

	/** 
	 * Gets the value of grupoCodigo
	 */
	public int getGrupoCodigo()
	{
		return grupoCodigo;
	}

	/** 
	 * Sets the value of idObservacion
	 */
	public void setIdObservacion(int idObservacion)
	{
		this.idObservacion = idObservacion;
	}

	/** 
	 * Gets the value of idObservacion
	 */
	public int getIdObservacion()
	{
		return idObservacion;
	}

	/**
	 * Method 'ObservacionGeneralPk'
	 * 
	 */
	public ObservacionGeneralPk()
	{
	}

	/**
	 * Method 'ObservacionGeneralPk'
	 * 
	 * @param grupoNumeroFicha
	 * @param grupoCodigo
	 * @param idObservacion
	 */
	public ObservacionGeneralPk(final String grupoNumeroFicha, final int grupoCodigo, final int idObservacion)
	{
		this.grupoNumeroFicha = grupoNumeroFicha;
		this.grupoCodigo = grupoCodigo;
		this.idObservacion = idObservacion;
	}

	/** 
	 * Sets the value of grupoCodigoNull
	 */
	public void setGrupoCodigoNull(boolean grupoCodigoNull)
	{
		this.grupoCodigoNull = grupoCodigoNull;
	}

	/** 
	 * Gets the value of grupoCodigoNull
	 */
	public boolean isGrupoCodigoNull()
	{
		return grupoCodigoNull;
	}

	/** 
	 * Sets the value of idObservacionNull
	 */
	public void setIdObservacionNull(boolean idObservacionNull)
	{
		this.idObservacionNull = idObservacionNull;
	}

	/** 
	 * Gets the value of idObservacionNull
	 */
	public boolean isIdObservacionNull()
	{
		return idObservacionNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ObservacionGeneralPk)) {
			return false;
		}
		
		final ObservacionGeneralPk _cast = (ObservacionGeneralPk) _other;
		if (grupoNumeroFicha == null ? _cast.grupoNumeroFicha != grupoNumeroFicha : !grupoNumeroFicha.equals( _cast.grupoNumeroFicha )) {
			return false;
		}
		
		if (grupoCodigo != _cast.grupoCodigo) {
			return false;
		}
		
		if (idObservacion != _cast.idObservacion) {
			return false;
		}
		
		if (grupoCodigoNull != _cast.grupoCodigoNull) {
			return false;
		}
		
		if (idObservacionNull != _cast.idObservacionNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (grupoNumeroFicha != null) {
			_hashCode = 29 * _hashCode + grupoNumeroFicha.hashCode();
		}
		
		_hashCode = 29 * _hashCode + grupoCodigo;
		_hashCode = 29 * _hashCode + idObservacion;
		_hashCode = 29 * _hashCode + (grupoCodigoNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (idObservacionNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.ObservacionGeneralPk: " );
		ret.append( "grupoNumeroFicha=" + grupoNumeroFicha );
		ret.append( ", grupoCodigo=" + grupoCodigo );
		ret.append( ", idObservacion=" + idObservacion );
		return ret.toString();
	}

}
