/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the programa table.
 */
public class ProgramaPk implements Serializable
{
	protected String codigoVersion;

	/** 
	 * Sets the value of codigoVersion
	 */
	public void setCodigoVersion(String codigoVersion)
	{
		this.codigoVersion = codigoVersion;
	}

	/** 
	 * Gets the value of codigoVersion
	 */
	public String getCodigoVersion()
	{
		return codigoVersion;
	}

	/**
	 * Method 'ProgramaPk'
	 * 
	 */
	public ProgramaPk()
	{
	}

	/**
	 * Method 'ProgramaPk'
	 * 
	 * @param codigoVersion
	 */
	public ProgramaPk(final String codigoVersion)
	{
		this.codigoVersion = codigoVersion;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ProgramaPk)) {
			return false;
		}
		
		final ProgramaPk _cast = (ProgramaPk) _other;
		if (codigoVersion == null ? _cast.codigoVersion != codigoVersion : !codigoVersion.equals( _cast.codigoVersion )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (codigoVersion != null) {
			_hashCode = 29 * _hashCode + codigoVersion.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.ProgramaPk: " );
		ret.append( "codigoVersion=" + codigoVersion );
		return ret.toString();
	}

}
