/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import co.edu.sena.controller.dao.*;
import co.edu.sena.controller.factory.*;
import co.edu.sena.controller.dao.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Programa implements Serializable
{
	/** 
	 * This attribute maps to the column codigo_version in the programa table.
	 */
	protected String codigoVersion;

	/** 
	 * This attribute maps to the column estado in the programa table.
	 */
	protected String estado;

	/** 
	 * This attribute maps to the column nombre in the programa table.
	 */
	protected String nombre;

	/**
	 * Method 'Programa'
	 * 
	 */
	public Programa()
	{
	}

	/**
	 * Method 'getCodigoVersion'
	 * 
	 * @return String
	 */
	public String getCodigoVersion()
	{
		return codigoVersion;
	}

	/**
	 * Method 'setCodigoVersion'
	 * 
	 * @param codigoVersion
	 */
	public void setCodigoVersion(String codigoVersion)
	{
		this.codigoVersion = codigoVersion;
	}

	/**
	 * Method 'getEstado'
	 * 
	 * @return String
	 */
	public String getEstado()
	{
		return estado;
	}

	/**
	 * Method 'setEstado'
	 * 
	 * @param estado
	 */
	public void setEstado(String estado)
	{
		this.estado = estado;
	}

	/**
	 * Method 'getNombre'
	 * 
	 * @return String
	 */
	public String getNombre()
	{
		return nombre;
	}

	/**
	 * Method 'setNombre'
	 * 
	 * @param nombre
	 */
	public void setNombre(String nombre)
	{
		this.nombre = nombre;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Programa)) {
			return false;
		}
		
		final Programa _cast = (Programa) _other;
		if (codigoVersion == null ? _cast.codigoVersion != codigoVersion : !codigoVersion.equals( _cast.codigoVersion )) {
			return false;
		}
		
		if (estado == null ? _cast.estado != estado : !estado.equals( _cast.estado )) {
			return false;
		}
		
		if (nombre == null ? _cast.nombre != nombre : !nombre.equals( _cast.nombre )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (codigoVersion != null) {
			_hashCode = 29 * _hashCode + codigoVersion.hashCode();
		}
		
		if (estado != null) {
			_hashCode = 29 * _hashCode + estado.hashCode();
		}
		
		if (nombre != null) {
			_hashCode = 29 * _hashCode + nombre.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ProgramaPk
	 */
	public ProgramaPk createPk()
	{
		return new ProgramaPk(codigoVersion);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.Programa: " );
		ret.append( "codigoVersion=" + codigoVersion );
		ret.append( ", estado=" + estado );
		ret.append( ", nombre=" + nombre );
		return ret.toString();
	}

}
