/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import co.edu.sena.controller.dao.*;
import co.edu.sena.controller.factory.*;
import co.edu.sena.controller.dao.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Rae implements Serializable
{
	/** 
	 * This attribute maps to the column codigo in the rae table.
	 */
	protected String codigo;

	/** 
	 * This attribute maps to the column denominacion in the rae table.
	 */
	protected String denominacion;

	/** 
	 * This attribute maps to the column competencia_codigo in the rae table.
	 */
	protected String competenciaCodigo;

	/** 
	 * This attribute maps to the column programa_codigo_version in the rae table.
	 */
	protected String programaCodigoVersion;

	/**
	 * Method 'Rae'
	 * 
	 */
	public Rae()
	{
	}

	/**
	 * Method 'getCodigo'
	 * 
	 * @return String
	 */
	public String getCodigo()
	{
		return codigo;
	}

	/**
	 * Method 'setCodigo'
	 * 
	 * @param codigo
	 */
	public void setCodigo(String codigo)
	{
		this.codigo = codigo;
	}

	/**
	 * Method 'getDenominacion'
	 * 
	 * @return String
	 */
	public String getDenominacion()
	{
		return denominacion;
	}

	/**
	 * Method 'setDenominacion'
	 * 
	 * @param denominacion
	 */
	public void setDenominacion(String denominacion)
	{
		this.denominacion = denominacion;
	}

	/**
	 * Method 'getCompetenciaCodigo'
	 * 
	 * @return String
	 */
	public String getCompetenciaCodigo()
	{
		return competenciaCodigo;
	}

	/**
	 * Method 'setCompetenciaCodigo'
	 * 
	 * @param competenciaCodigo
	 */
	public void setCompetenciaCodigo(String competenciaCodigo)
	{
		this.competenciaCodigo = competenciaCodigo;
	}

	/**
	 * Method 'getProgramaCodigoVersion'
	 * 
	 * @return String
	 */
	public String getProgramaCodigoVersion()
	{
		return programaCodigoVersion;
	}

	/**
	 * Method 'setProgramaCodigoVersion'
	 * 
	 * @param programaCodigoVersion
	 */
	public void setProgramaCodigoVersion(String programaCodigoVersion)
	{
		this.programaCodigoVersion = programaCodigoVersion;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Rae)) {
			return false;
		}
		
		final Rae _cast = (Rae) _other;
		if (codigo == null ? _cast.codigo != codigo : !codigo.equals( _cast.codigo )) {
			return false;
		}
		
		if (denominacion == null ? _cast.denominacion != denominacion : !denominacion.equals( _cast.denominacion )) {
			return false;
		}
		
		if (competenciaCodigo == null ? _cast.competenciaCodigo != competenciaCodigo : !competenciaCodigo.equals( _cast.competenciaCodigo )) {
			return false;
		}
		
		if (programaCodigoVersion == null ? _cast.programaCodigoVersion != programaCodigoVersion : !programaCodigoVersion.equals( _cast.programaCodigoVersion )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (codigo != null) {
			_hashCode = 29 * _hashCode + codigo.hashCode();
		}
		
		if (denominacion != null) {
			_hashCode = 29 * _hashCode + denominacion.hashCode();
		}
		
		if (competenciaCodigo != null) {
			_hashCode = 29 * _hashCode + competenciaCodigo.hashCode();
		}
		
		if (programaCodigoVersion != null) {
			_hashCode = 29 * _hashCode + programaCodigoVersion.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return RaePk
	 */
	public RaePk createPk()
	{
		return new RaePk(codigo, competenciaCodigo, programaCodigoVersion);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.Rae: " );
		ret.append( "codigo=" + codigo );
		ret.append( ", denominacion=" + denominacion );
		ret.append( ", competenciaCodigo=" + competenciaCodigo );
		ret.append( ", programaCodigoVersion=" + programaCodigoVersion );
		return ret.toString();
	}

}
