/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the rae table.
 */
public class RaePk implements Serializable
{
	protected String codigo;

	protected String competenciaCodigo;

	protected String programaCodigoVersion;

	/** 
	 * Sets the value of codigo
	 */
	public void setCodigo(String codigo)
	{
		this.codigo = codigo;
	}

	/** 
	 * Gets the value of codigo
	 */
	public String getCodigo()
	{
		return codigo;
	}

	/** 
	 * Sets the value of competenciaCodigo
	 */
	public void setCompetenciaCodigo(String competenciaCodigo)
	{
		this.competenciaCodigo = competenciaCodigo;
	}

	/** 
	 * Gets the value of competenciaCodigo
	 */
	public String getCompetenciaCodigo()
	{
		return competenciaCodigo;
	}

	/** 
	 * Sets the value of programaCodigoVersion
	 */
	public void setProgramaCodigoVersion(String programaCodigoVersion)
	{
		this.programaCodigoVersion = programaCodigoVersion;
	}

	/** 
	 * Gets the value of programaCodigoVersion
	 */
	public String getProgramaCodigoVersion()
	{
		return programaCodigoVersion;
	}

	/**
	 * Method 'RaePk'
	 * 
	 */
	public RaePk()
	{
	}

	/**
	 * Method 'RaePk'
	 * 
	 * @param codigo
	 * @param competenciaCodigo
	 * @param programaCodigoVersion
	 */
	public RaePk(final String codigo, final String competenciaCodigo, final String programaCodigoVersion)
	{
		this.codigo = codigo;
		this.competenciaCodigo = competenciaCodigo;
		this.programaCodigoVersion = programaCodigoVersion;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof RaePk)) {
			return false;
		}
		
		final RaePk _cast = (RaePk) _other;
		if (codigo == null ? _cast.codigo != codigo : !codigo.equals( _cast.codigo )) {
			return false;
		}
		
		if (competenciaCodigo == null ? _cast.competenciaCodigo != competenciaCodigo : !competenciaCodigo.equals( _cast.competenciaCodigo )) {
			return false;
		}
		
		if (programaCodigoVersion == null ? _cast.programaCodigoVersion != programaCodigoVersion : !programaCodigoVersion.equals( _cast.programaCodigoVersion )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (codigo != null) {
			_hashCode = 29 * _hashCode + codigo.hashCode();
		}
		
		if (competenciaCodigo != null) {
			_hashCode = 29 * _hashCode + competenciaCodigo.hashCode();
		}
		
		if (programaCodigoVersion != null) {
			_hashCode = 29 * _hashCode + programaCodigoVersion.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.RaePk: " );
		ret.append( "codigo=" + codigo );
		ret.append( ", competenciaCodigo=" + competenciaCodigo );
		ret.append( ", programaCodigoVersion=" + programaCodigoVersion );
		return ret.toString();
	}

}
