/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the respuesta_grupo table.
 */
public class RespuestaGrupoPk implements Serializable
{
	protected String ficha;

	protected int grupoCodigo;

	protected String listaChequeo;

	protected int idItem;

	/** 
	 * This attribute represents whether the primitive attribute grupoCodigo is null.
	 */
	protected boolean grupoCodigoNull;

	/** 
	 * This attribute represents whether the primitive attribute idItem is null.
	 */
	protected boolean idItemNull;

	/** 
	 * Sets the value of ficha
	 */
	public void setFicha(String ficha)
	{
		this.ficha = ficha;
	}

	/** 
	 * Gets the value of ficha
	 */
	public String getFicha()
	{
		return ficha;
	}

	/** 
	 * Sets the value of grupoCodigo
	 */
	public void setGrupoCodigo(int grupoCodigo)
	{
		this.grupoCodigo = grupoCodigo;
	}

	/** 
	 * Gets the value of grupoCodigo
	 */
	public int getGrupoCodigo()
	{
		return grupoCodigo;
	}

	/** 
	 * Sets the value of listaChequeo
	 */
	public void setListaChequeo(String listaChequeo)
	{
		this.listaChequeo = listaChequeo;
	}

	/** 
	 * Gets the value of listaChequeo
	 */
	public String getListaChequeo()
	{
		return listaChequeo;
	}

	/** 
	 * Sets the value of idItem
	 */
	public void setIdItem(int idItem)
	{
		this.idItem = idItem;
	}

	/** 
	 * Gets the value of idItem
	 */
	public int getIdItem()
	{
		return idItem;
	}

	/**
	 * Method 'RespuestaGrupoPk'
	 * 
	 */
	public RespuestaGrupoPk()
	{
	}

	/**
	 * Method 'RespuestaGrupoPk'
	 * 
	 * @param ficha
	 * @param grupoCodigo
	 * @param listaChequeo
	 * @param idItem
	 */
	public RespuestaGrupoPk(final String ficha, final int grupoCodigo, final String listaChequeo, final int idItem)
	{
		this.ficha = ficha;
		this.grupoCodigo = grupoCodigo;
		this.listaChequeo = listaChequeo;
		this.idItem = idItem;
	}

	/** 
	 * Sets the value of grupoCodigoNull
	 */
	public void setGrupoCodigoNull(boolean grupoCodigoNull)
	{
		this.grupoCodigoNull = grupoCodigoNull;
	}

	/** 
	 * Gets the value of grupoCodigoNull
	 */
	public boolean isGrupoCodigoNull()
	{
		return grupoCodigoNull;
	}

	/** 
	 * Sets the value of idItemNull
	 */
	public void setIdItemNull(boolean idItemNull)
	{
		this.idItemNull = idItemNull;
	}

	/** 
	 * Gets the value of idItemNull
	 */
	public boolean isIdItemNull()
	{
		return idItemNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof RespuestaGrupoPk)) {
			return false;
		}
		
		final RespuestaGrupoPk _cast = (RespuestaGrupoPk) _other;
		if (ficha == null ? _cast.ficha != ficha : !ficha.equals( _cast.ficha )) {
			return false;
		}
		
		if (grupoCodigo != _cast.grupoCodigo) {
			return false;
		}
		
		if (listaChequeo == null ? _cast.listaChequeo != listaChequeo : !listaChequeo.equals( _cast.listaChequeo )) {
			return false;
		}
		
		if (idItem != _cast.idItem) {
			return false;
		}
		
		if (grupoCodigoNull != _cast.grupoCodigoNull) {
			return false;
		}
		
		if (idItemNull != _cast.idItemNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (ficha != null) {
			_hashCode = 29 * _hashCode + ficha.hashCode();
		}
		
		_hashCode = 29 * _hashCode + grupoCodigo;
		if (listaChequeo != null) {
			_hashCode = 29 * _hashCode + listaChequeo.hashCode();
		}
		
		_hashCode = 29 * _hashCode + idItem;
		_hashCode = 29 * _hashCode + (grupoCodigoNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (idItemNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.RespuestaGrupoPk: " );
		ret.append( "ficha=" + ficha );
		ret.append( ", grupoCodigo=" + grupoCodigo );
		ret.append( ", listaChequeo=" + listaChequeo );
		ret.append( ", idItem=" + idItem );
		return ret.toString();
	}

}
