/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import co.edu.sena.controller.dao.*;
import co.edu.sena.controller.factory.*;
import co.edu.sena.controller.dao.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class RespuestaGrupo implements Serializable
{
	/** 
	 * This attribute maps to the column ficha in the respuesta_grupo table.
	 */
	protected String ficha;

	/** 
	 * This attribute maps to the column grupo_codigo in the respuesta_grupo table.
	 */
	protected int grupoCodigo;

	/** 
	 * This attribute maps to the column lista_chequeo in the respuesta_grupo table.
	 */
	protected String listaChequeo;

	/** 
	 * This attribute maps to the column id_item in the respuesta_grupo table.
	 */
	protected int idItem;

	/** 
	 * This attribute maps to the column valoracion_valor in the respuesta_grupo table.
	 */
	protected String valoracionValor;

	/** 
	 * This attribute maps to the column fecha in the respuesta_grupo table.
	 */
	protected Date fecha;

	/**
	 * Method 'RespuestaGrupo'
	 * 
	 */
	public RespuestaGrupo()
	{
	}

	/**
	 * Method 'getFicha'
	 * 
	 * @return String
	 */
	public String getFicha()
	{
		return ficha;
	}

	/**
	 * Method 'setFicha'
	 * 
	 * @param ficha
	 */
	public void setFicha(String ficha)
	{
		this.ficha = ficha;
	}

	/**
	 * Method 'getGrupoCodigo'
	 * 
	 * @return int
	 */
	public int getGrupoCodigo()
	{
		return grupoCodigo;
	}

	/**
	 * Method 'setGrupoCodigo'
	 * 
	 * @param grupoCodigo
	 */
	public void setGrupoCodigo(int grupoCodigo)
	{
		this.grupoCodigo = grupoCodigo;
	}

	/**
	 * Method 'getListaChequeo'
	 * 
	 * @return String
	 */
	public String getListaChequeo()
	{
		return listaChequeo;
	}

	/**
	 * Method 'setListaChequeo'
	 * 
	 * @param listaChequeo
	 */
	public void setListaChequeo(String listaChequeo)
	{
		this.listaChequeo = listaChequeo;
	}

	/**
	 * Method 'getIdItem'
	 * 
	 * @return int
	 */
	public int getIdItem()
	{
		return idItem;
	}

	/**
	 * Method 'setIdItem'
	 * 
	 * @param idItem
	 */
	public void setIdItem(int idItem)
	{
		this.idItem = idItem;
	}

	/**
	 * Method 'getValoracionValor'
	 * 
	 * @return String
	 */
	public String getValoracionValor()
	{
		return valoracionValor;
	}

	/**
	 * Method 'setValoracionValor'
	 * 
	 * @param valoracionValor
	 */
	public void setValoracionValor(String valoracionValor)
	{
		this.valoracionValor = valoracionValor;
	}

	/**
	 * Method 'getFecha'
	 * 
	 * @return Date
	 */
	public Date getFecha()
	{
		return fecha;
	}

	/**
	 * Method 'setFecha'
	 * 
	 * @param fecha
	 */
	public void setFecha(Date fecha)
	{
		this.fecha = fecha;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof RespuestaGrupo)) {
			return false;
		}
		
		final RespuestaGrupo _cast = (RespuestaGrupo) _other;
		if (ficha == null ? _cast.ficha != ficha : !ficha.equals( _cast.ficha )) {
			return false;
		}
		
		if (grupoCodigo != _cast.grupoCodigo) {
			return false;
		}
		
		if (listaChequeo == null ? _cast.listaChequeo != listaChequeo : !listaChequeo.equals( _cast.listaChequeo )) {
			return false;
		}
		
		if (idItem != _cast.idItem) {
			return false;
		}
		
		if (valoracionValor == null ? _cast.valoracionValor != valoracionValor : !valoracionValor.equals( _cast.valoracionValor )) {
			return false;
		}
		
		if (fecha == null ? _cast.fecha != fecha : !fecha.equals( _cast.fecha )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (ficha != null) {
			_hashCode = 29 * _hashCode + ficha.hashCode();
		}
		
		_hashCode = 29 * _hashCode + grupoCodigo;
		if (listaChequeo != null) {
			_hashCode = 29 * _hashCode + listaChequeo.hashCode();
		}
		
		_hashCode = 29 * _hashCode + idItem;
		if (valoracionValor != null) {
			_hashCode = 29 * _hashCode + valoracionValor.hashCode();
		}
		
		if (fecha != null) {
			_hashCode = 29 * _hashCode + fecha.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return RespuestaGrupoPk
	 */
	public RespuestaGrupoPk createPk()
	{
		return new RespuestaGrupoPk(ficha, grupoCodigo, listaChequeo, idItem);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.RespuestaGrupo: " );
		ret.append( "ficha=" + ficha );
		ret.append( ", grupoCodigo=" + grupoCodigo );
		ret.append( ", listaChequeo=" + listaChequeo );
		ret.append( ", idItem=" + idItem );
		ret.append( ", valoracionValor=" + valoracionValor );
		ret.append( ", fecha=" + fecha );
		return ret.toString();
	}

}
