/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the trimestre table.
 */
public class TrimestrePk implements Serializable
{
	protected String idTrimestre;

	protected String jornadaNombre;

	/** 
	 * Sets the value of idTrimestre
	 */
	public void setIdTrimestre(String idTrimestre)
	{
		this.idTrimestre = idTrimestre;
	}

	/** 
	 * Gets the value of idTrimestre
	 */
	public String getIdTrimestre()
	{
		return idTrimestre;
	}

	/** 
	 * Sets the value of jornadaNombre
	 */
	public void setJornadaNombre(String jornadaNombre)
	{
		this.jornadaNombre = jornadaNombre;
	}

	/** 
	 * Gets the value of jornadaNombre
	 */
	public String getJornadaNombre()
	{
		return jornadaNombre;
	}

	/**
	 * Method 'TrimestrePk'
	 * 
	 */
	public TrimestrePk()
	{
	}

	/**
	 * Method 'TrimestrePk'
	 * 
	 * @param idTrimestre
	 * @param jornadaNombre
	 */
	public TrimestrePk(final String idTrimestre, final String jornadaNombre)
	{
		this.idTrimestre = idTrimestre;
		this.jornadaNombre = jornadaNombre;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TrimestrePk)) {
			return false;
		}
		
		final TrimestrePk _cast = (TrimestrePk) _other;
		if (idTrimestre == null ? _cast.idTrimestre != idTrimestre : !idTrimestre.equals( _cast.idTrimestre )) {
			return false;
		}
		
		if (jornadaNombre == null ? _cast.jornadaNombre != jornadaNombre : !jornadaNombre.equals( _cast.jornadaNombre )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (idTrimestre != null) {
			_hashCode = 29 * _hashCode + idTrimestre.hashCode();
		}
		
		if (jornadaNombre != null) {
			_hashCode = 29 * _hashCode + jornadaNombre.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.TrimestrePk: " );
		ret.append( "idTrimestre=" + idTrimestre );
		ret.append( ", jornadaNombre=" + jornadaNombre );
		return ret.toString();
	}

}
