/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the valoracion table.
 */
public class ValoracionPk implements Serializable
{
	protected String valor;

	/** 
	 * Sets the value of valor
	 */
	public void setValor(String valor)
	{
		this.valor = valor;
	}

	/** 
	 * Gets the value of valor
	 */
	public String getValor()
	{
		return valor;
	}

	/**
	 * Method 'ValoracionPk'
	 * 
	 */
	public ValoracionPk()
	{
	}

	/**
	 * Method 'ValoracionPk'
	 * 
	 * @param valor
	 */
	public ValoracionPk(final String valor)
	{
		this.valor = valor;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ValoracionPk)) {
			return false;
		}
		
		final ValoracionPk _cast = (ValoracionPk) _other;
		if (valor == null ? _cast.valor != valor : !valor.equals( _cast.valor )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (valor != null) {
			_hashCode = 29 * _hashCode + valor.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.ValoracionPk: " );
		ret.append( "valor=" + valor );
		return ret.toString();
	}

}
