/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.model.dao.dto;

import co.edu.sena.controller.dao.*;
import co.edu.sena.controller.factory.*;
import co.edu.sena.controller.dao.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Valoracion implements Serializable
{
	/** 
	 * This attribute maps to the column valor in the valoracion table.
	 */
	protected String valor;

	/** 
	 * This attribute maps to the column estado in the valoracion table.
	 */
	protected short estado;

	/**
	 * Method 'Valoracion'
	 * 
	 */
	public Valoracion()
	{
	}

	/**
	 * Method 'getValor'
	 * 
	 * @return String
	 */
	public String getValor()
	{
		return valor;
	}

	/**
	 * Method 'setValor'
	 * 
	 * @param valor
	 */
	public void setValor(String valor)
	{
		this.valor = valor;
	}

	/**
	 * Method 'getEstado'
	 * 
	 * @return short
	 */
	public short getEstado()
	{
		return estado;
	}

	/**
	 * Method 'setEstado'
	 * 
	 * @param estado
	 */
	public void setEstado(short estado)
	{
		this.estado = estado;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Valoracion)) {
			return false;
		}
		
		final Valoracion _cast = (Valoracion) _other;
		if (valor == null ? _cast.valor != valor : !valor.equals( _cast.valor )) {
			return false;
		}
		
		if (estado != _cast.estado) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (valor != null) {
			_hashCode = 29 * _hashCode + valor.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) estado;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ValoracionPk
	 */
	public ValoracionPk createPk()
	{
		return new ValoracionPk(valor);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "co.edu.sena.model.dao.dto.Valoracion: " );
		ret.append( "valor=" + valor );
		ret.append( ", estado=" + estado );
		return ret.toString();
	}

}
