/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controller.dao.jdbc;

import co.edu.sena.controller.dao.*;
import co.edu.sena.controller.factory.*;
import co.edu.sena.model.dao.dto.*;
import co.edu.sena.controller.dao.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class FichaDaoImpl extends AbstractDAO implements FichaDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT numero_ficha, programa_codigo_version, jornada_nombre, estado FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( numero_ficha, programa_codigo_version, jornada_nombre, estado ) VALUES ( ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET numero_ficha = ?, programa_codigo_version = ?, jornada_nombre = ?, estado = ? WHERE numero_ficha = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE numero_ficha = ?";

	/** 
	 * Index of column numero_ficha
	 */
	protected static final int COLUMN_NUMERO_FICHA = 1;

	/** 
	 * Index of column programa_codigo_version
	 */
	protected static final int COLUMN_PROGRAMA_CODIGO_VERSION = 2;

	/** 
	 * Index of column jornada_nombre
	 */
	protected static final int COLUMN_JORNADA_NOMBRE = 3;

	/** 
	 * Index of column estado
	 */
	protected static final int COLUMN_ESTADO = 4;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 4;

	/** 
	 * Index of primary-key column numero_ficha
	 */
	protected static final int PK_COLUMN_NUMERO_FICHA = 1;

	/** 
	 * Inserts a new row in the ficha table.
	 */
	public FichaPk insert(Ficha dto) throws FichaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setString( index++, dto.getNumeroFicha() );
			stmt.setString( index++, dto.getProgramaCodigoVersion() );
			stmt.setString( index++, dto.getJornadaNombre() );
			stmt.setString( index++, dto.getEstado() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new FichaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the ficha table.
	 */
	public void update(FichaPk pk, Ficha dto) throws FichaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setString( index++, dto.getNumeroFicha() );
			stmt.setString( index++, dto.getProgramaCodigoVersion() );
			stmt.setString( index++, dto.getJornadaNombre() );
			stmt.setString( index++, dto.getEstado() );
			stmt.setString( 5, pk.getNumeroFicha() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new FichaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the ficha table.
	 */
	public void delete(FichaPk pk) throws FichaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setString( 1, pk.getNumeroFicha() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new FichaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the ficha table that matches the specified primary-key value.
	 */
	public Ficha findByPrimaryKey(FichaPk pk) throws FichaDaoException
	{
		return findByPrimaryKey( pk.getNumeroFicha() );
	}

	/** 
	 * Returns all rows from the ficha table that match the criteria 'numero_ficha = :numeroFicha'.
	 */
	public Ficha findByPrimaryKey(String numeroFicha) throws FichaDaoException
	{
		Ficha ret[] = findByDynamicSelect( SQL_SELECT + " WHERE numero_ficha = ?", new Object[] { numeroFicha } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the ficha table that match the criteria ''.
	 */
	public Ficha[] findAll() throws FichaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY numero_ficha", null );
	}

	/** 
	 * Returns all rows from the ficha table that match the criteria 'jornada_nombre = :jornadaNombre'.
	 */
	public Ficha[] findByJornada(String jornadaNombre) throws FichaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE jornada_nombre = ?", new Object[] { jornadaNombre } );
	}

	/** 
	 * Returns all rows from the ficha table that match the criteria 'programa_codigo_version = :programaCodigoVersion'.
	 */
	public Ficha[] findByPrograma(String programaCodigoVersion) throws FichaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE programa_codigo_version = ?", new Object[] { programaCodigoVersion } );
	}

	/** 
	 * Returns all rows from the ficha table that match the criteria 'numero_ficha = :numeroFicha'.
	 */
	public Ficha[] findWhereNumeroFichaEquals(String numeroFicha) throws FichaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE numero_ficha = ? ORDER BY numero_ficha", new Object[] { numeroFicha } );
	}

	/** 
	 * Returns all rows from the ficha table that match the criteria 'programa_codigo_version = :programaCodigoVersion'.
	 */
	public Ficha[] findWhereProgramaCodigoVersionEquals(String programaCodigoVersion) throws FichaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE programa_codigo_version = ? ORDER BY programa_codigo_version", new Object[] { programaCodigoVersion } );
	}

	/** 
	 * Returns all rows from the ficha table that match the criteria 'jornada_nombre = :jornadaNombre'.
	 */
	public Ficha[] findWhereJornadaNombreEquals(String jornadaNombre) throws FichaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE jornada_nombre = ? ORDER BY jornada_nombre", new Object[] { jornadaNombre } );
	}

	/** 
	 * Returns all rows from the ficha table that match the criteria 'estado = :estado'.
	 */
	public Ficha[] findWhereEstadoEquals(String estado) throws FichaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE estado = ? ORDER BY estado", new Object[] { estado } );
	}

	/**
	 * Method 'FichaDaoImpl'
	 * 
	 */
	public FichaDaoImpl()
	{
	}

	/**
	 * Method 'FichaDaoImpl'
	 * 
	 * @param userConn
	 */
	public FichaDaoImpl(final Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "observador_de_proyectos.ficha";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Ficha fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Ficha dto = new Ficha();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Ficha[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Ficha dto = new Ficha();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Ficha ret[] = new Ficha[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Ficha dto, ResultSet rs) throws SQLException
	{
		dto.setNumeroFicha( rs.getString( COLUMN_NUMERO_FICHA ) );
		dto.setProgramaCodigoVersion( rs.getString( COLUMN_PROGRAMA_CODIGO_VERSION ) );
		dto.setJornadaNombre( rs.getString( COLUMN_JORNADA_NOMBRE ) );
		dto.setEstado( rs.getString( COLUMN_ESTADO ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Ficha dto)
	{
	}

	/** 
	 * Returns all rows from the ficha table that match the specified arbitrary SQL statement
	 */
	public Ficha[] findByDynamicSelect(String sql, Object[] sqlParams) throws FichaDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new FichaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the ficha table that match the specified arbitrary SQL statement
	 */
	public Ficha[] findByDynamicWhere(String sql, Object[] sqlParams) throws FichaDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new FichaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
