/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controller.dao.jdbc;

import co.edu.sena.controller.dao.*;
import co.edu.sena.controller.factory.*;
import co.edu.sena.model.dao.dto.*;
import co.edu.sena.controller.dao.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class ListaChequeoDaoImpl extends AbstractDAO implements ListaChequeoDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT id_lista, estado, programa_codigo_version FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( id_lista, estado, programa_codigo_version ) VALUES ( ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET id_lista = ?, estado = ?, programa_codigo_version = ? WHERE id_lista = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE id_lista = ?";

	/** 
	 * Index of column id_lista
	 */
	protected static final int COLUMN_ID_LISTA = 1;

	/** 
	 * Index of column estado
	 */
	protected static final int COLUMN_ESTADO = 2;

	/** 
	 * Index of column programa_codigo_version
	 */
	protected static final int COLUMN_PROGRAMA_CODIGO_VERSION = 3;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 3;

	/** 
	 * Index of primary-key column id_lista
	 */
	protected static final int PK_COLUMN_ID_LISTA = 1;

	/** 
	 * Inserts a new row in the lista_chequeo table.
	 */
	public ListaChequeoPk insert(ListaChequeo dto) throws ListaChequeoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setString( index++, dto.getIdLista() );
			stmt.setShort( index++, dto.getEstado() );
			stmt.setString( index++, dto.getProgramaCodigoVersion() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ListaChequeoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the lista_chequeo table.
	 */
	public void update(ListaChequeoPk pk, ListaChequeo dto) throws ListaChequeoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setString( index++, dto.getIdLista() );
			stmt.setShort( index++, dto.getEstado() );
			stmt.setString( index++, dto.getProgramaCodigoVersion() );
			stmt.setString( 4, pk.getIdLista() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ListaChequeoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the lista_chequeo table.
	 */
	public void delete(ListaChequeoPk pk) throws ListaChequeoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setString( 1, pk.getIdLista() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ListaChequeoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the lista_chequeo table that matches the specified primary-key value.
	 */
	public ListaChequeo findByPrimaryKey(ListaChequeoPk pk) throws ListaChequeoDaoException
	{
		return findByPrimaryKey( pk.getIdLista() );
	}

	/** 
	 * Returns all rows from the lista_chequeo table that match the criteria 'id_lista = :idLista'.
	 */
	public ListaChequeo findByPrimaryKey(String idLista) throws ListaChequeoDaoException
	{
		ListaChequeo ret[] = findByDynamicSelect( SQL_SELECT + " WHERE id_lista = ?", new Object[] { idLista } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the lista_chequeo table that match the criteria ''.
	 */
	public ListaChequeo[] findAll() throws ListaChequeoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY id_lista", null );
	}

	/** 
	 * Returns all rows from the lista_chequeo table that match the criteria 'programa_codigo_version = :programaCodigoVersion'.
	 */
	public ListaChequeo[] findByPrograma(String programaCodigoVersion) throws ListaChequeoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE programa_codigo_version = ?", new Object[] { programaCodigoVersion } );
	}

	/** 
	 * Returns all rows from the lista_chequeo table that match the criteria 'id_lista = :idLista'.
	 */
	public ListaChequeo[] findWhereIdListaEquals(String idLista) throws ListaChequeoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE id_lista = ? ORDER BY id_lista", new Object[] { idLista } );
	}

	/** 
	 * Returns all rows from the lista_chequeo table that match the criteria 'estado = :estado'.
	 */
	public ListaChequeo[] findWhereEstadoEquals(short estado) throws ListaChequeoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE estado = ? ORDER BY estado", new Object[] {  new Short(estado) } );
	}

	/** 
	 * Returns all rows from the lista_chequeo table that match the criteria 'programa_codigo_version = :programaCodigoVersion'.
	 */
	public ListaChequeo[] findWhereProgramaCodigoVersionEquals(String programaCodigoVersion) throws ListaChequeoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE programa_codigo_version = ? ORDER BY programa_codigo_version", new Object[] { programaCodigoVersion } );
	}

	/**
	 * Method 'ListaChequeoDaoImpl'
	 * 
	 */
	public ListaChequeoDaoImpl()
	{
	}

	/**
	 * Method 'ListaChequeoDaoImpl'
	 * 
	 * @param userConn
	 */
	public ListaChequeoDaoImpl(final Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "observador_de_proyectos.lista_chequeo";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected ListaChequeo fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			ListaChequeo dto = new ListaChequeo();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected ListaChequeo[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			ListaChequeo dto = new ListaChequeo();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		ListaChequeo ret[] = new ListaChequeo[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(ListaChequeo dto, ResultSet rs) throws SQLException
	{
		dto.setIdLista( rs.getString( COLUMN_ID_LISTA ) );
		dto.setEstado( rs.getShort( COLUMN_ESTADO ) );
		dto.setProgramaCodigoVersion( rs.getString( COLUMN_PROGRAMA_CODIGO_VERSION ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(ListaChequeo dto)
	{
	}

	/** 
	 * Returns all rows from the lista_chequeo table that match the specified arbitrary SQL statement
	 */
	public ListaChequeo[] findByDynamicSelect(String sql, Object[] sqlParams) throws ListaChequeoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ListaChequeoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the lista_chequeo table that match the specified arbitrary SQL statement
	 */
	public ListaChequeo[] findByDynamicWhere(String sql, Object[] sqlParams) throws ListaChequeoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ListaChequeoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
