/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controller.dao.jdbc;

import co.edu.sena.controller.dao.*;
import co.edu.sena.controller.factory.*;
import java.util.Date;
import co.edu.sena.model.dao.dto.*;
import co.edu.sena.controller.dao.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class ObservacionItemDaoImpl extends AbstractDAO implements ObservacionItemDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT id_observacion, numero_ficha, grupo_codigo, lista_chequeo, id_item, observacion, jurados, fecha, usuario FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( id_observacion, numero_ficha, grupo_codigo, lista_chequeo, id_item, observacion, jurados, fecha, usuario ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET id_observacion = ?, numero_ficha = ?, grupo_codigo = ?, lista_chequeo = ?, id_item = ?, observacion = ?, jurados = ?, fecha = ?, usuario = ? WHERE id_observacion = ? AND numero_ficha = ? AND grupo_codigo = ? AND lista_chequeo = ? AND id_item = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE id_observacion = ? AND numero_ficha = ? AND grupo_codigo = ? AND lista_chequeo = ? AND id_item = ?";

	/** 
	 * Index of column id_observacion
	 */
	protected static final int COLUMN_ID_OBSERVACION = 1;

	/** 
	 * Index of column numero_ficha
	 */
	protected static final int COLUMN_NUMERO_FICHA = 2;

	/** 
	 * Index of column grupo_codigo
	 */
	protected static final int COLUMN_GRUPO_CODIGO = 3;

	/** 
	 * Index of column lista_chequeo
	 */
	protected static final int COLUMN_LISTA_CHEQUEO = 4;

	/** 
	 * Index of column id_item
	 */
	protected static final int COLUMN_ID_ITEM = 5;

	/** 
	 * Index of column observacion
	 */
	protected static final int COLUMN_OBSERVACION = 6;

	/** 
	 * Index of column jurados
	 */
	protected static final int COLUMN_JURADOS = 7;

	/** 
	 * Index of column fecha
	 */
	protected static final int COLUMN_FECHA = 8;

	/** 
	 * Index of column usuario
	 */
	protected static final int COLUMN_USUARIO = 9;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 9;

	/** 
	 * Index of primary-key column id_observacion
	 */
	protected static final int PK_COLUMN_ID_OBSERVACION = 1;

	/** 
	 * Index of primary-key column numero_ficha
	 */
	protected static final int PK_COLUMN_NUMERO_FICHA = 2;

	/** 
	 * Index of primary-key column grupo_codigo
	 */
	protected static final int PK_COLUMN_GRUPO_CODIGO = 3;

	/** 
	 * Index of primary-key column lista_chequeo
	 */
	protected static final int PK_COLUMN_LISTA_CHEQUEO = 4;

	/** 
	 * Index of primary-key column id_item
	 */
	protected static final int PK_COLUMN_ID_ITEM = 5;

	/** 
	 * Inserts a new row in the observacion_item table.
	 */
	public ObservacionItemPk insert(ObservacionItem dto) throws ObservacionItemDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getIdObservacion() );
			stmt.setString( index++, dto.getNumeroFicha() );
			stmt.setInt( index++, dto.getGrupoCodigo() );
			stmt.setString( index++, dto.getListaChequeo() );
			stmt.setInt( index++, dto.getIdItem() );
			stmt.setString( index++, dto.getObservacion() );
			stmt.setString( index++, dto.getJurados() );
			stmt.setTimestamp(index++, dto.getFecha()==null ? null : new java.sql.Timestamp( dto.getFecha().getTime() ) );
			stmt.setString( index++, dto.getUsuario() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ObservacionItemDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the observacion_item table.
	 */
	public void update(ObservacionItemPk pk, ObservacionItem dto) throws ObservacionItemDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getIdObservacion() );
			stmt.setString( index++, dto.getNumeroFicha() );
			stmt.setInt( index++, dto.getGrupoCodigo() );
			stmt.setString( index++, dto.getListaChequeo() );
			stmt.setInt( index++, dto.getIdItem() );
			stmt.setString( index++, dto.getObservacion() );
			stmt.setString( index++, dto.getJurados() );
			stmt.setTimestamp(index++, dto.getFecha()==null ? null : new java.sql.Timestamp( dto.getFecha().getTime() ) );
			stmt.setString( index++, dto.getUsuario() );
			stmt.setInt( 10, pk.getIdObservacion() );
			stmt.setString( 11, pk.getNumeroFicha() );
			stmt.setInt( 12, pk.getGrupoCodigo() );
			stmt.setString( 13, pk.getListaChequeo() );
			stmt.setInt( 14, pk.getIdItem() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ObservacionItemDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the observacion_item table.
	 */
	public void delete(ObservacionItemPk pk) throws ObservacionItemDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdObservacion() );
			stmt.setString( 2, pk.getNumeroFicha() );
			stmt.setInt( 3, pk.getGrupoCodigo() );
			stmt.setString( 4, pk.getListaChequeo() );
			stmt.setInt( 5, pk.getIdItem() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ObservacionItemDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the observacion_item table that matches the specified primary-key value.
	 */
	public ObservacionItem findByPrimaryKey(ObservacionItemPk pk) throws ObservacionItemDaoException
	{
		return findByPrimaryKey( pk.getIdObservacion(), pk.getNumeroFicha(), pk.getGrupoCodigo(), pk.getListaChequeo(), pk.getIdItem() );
	}

	/** 
	 * Returns all rows from the observacion_item table that match the criteria 'id_observacion = :idObservacion AND numero_ficha = :numeroFicha AND grupo_codigo = :grupoCodigo AND lista_chequeo = :listaChequeo AND id_item = :idItem'.
	 */
	public ObservacionItem findByPrimaryKey(int idObservacion, String numeroFicha, int grupoCodigo, String listaChequeo, int idItem) throws ObservacionItemDaoException
	{
		ObservacionItem ret[] = findByDynamicSelect( SQL_SELECT + " WHERE id_observacion = ? AND numero_ficha = ? AND grupo_codigo = ? AND lista_chequeo = ? AND id_item = ?", new Object[] {  new Integer(idObservacion), numeroFicha,  new Integer(grupoCodigo), listaChequeo,  new Integer(idItem) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the observacion_item table that match the criteria ''.
	 */
	public ObservacionItem[] findAll() throws ObservacionItemDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY id_observacion, numero_ficha, grupo_codigo, lista_chequeo, id_item", null );
	}

	/** 
	 * Returns all rows from the observacion_item table that match the criteria 'numero_ficha = :numeroFicha AND grupo_codigo = :grupoCodigo AND lista_chequeo = :listaChequeo AND id_item = :idItem'.
	 */
	public ObservacionItem[] findByRespuestaGrupo(String numeroFicha, int grupoCodigo, String listaChequeo, int idItem) throws ObservacionItemDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE numero_ficha = ? AND grupo_codigo = ? AND lista_chequeo = ? AND id_item = ?", new Object[] { numeroFicha,  new Integer(grupoCodigo), listaChequeo,  new Integer(idItem) } );
	}

	/** 
	 * Returns all rows from the observacion_item table that match the criteria 'id_observacion = :idObservacion'.
	 */
	public ObservacionItem[] findWhereIdObservacionEquals(int idObservacion) throws ObservacionItemDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE id_observacion = ? ORDER BY id_observacion", new Object[] {  new Integer(idObservacion) } );
	}

	/** 
	 * Returns all rows from the observacion_item table that match the criteria 'numero_ficha = :numeroFicha'.
	 */
	public ObservacionItem[] findWhereNumeroFichaEquals(String numeroFicha) throws ObservacionItemDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE numero_ficha = ? ORDER BY numero_ficha", new Object[] { numeroFicha } );
	}

	/** 
	 * Returns all rows from the observacion_item table that match the criteria 'grupo_codigo = :grupoCodigo'.
	 */
	public ObservacionItem[] findWhereGrupoCodigoEquals(int grupoCodigo) throws ObservacionItemDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE grupo_codigo = ? ORDER BY grupo_codigo", new Object[] {  new Integer(grupoCodigo) } );
	}

	/** 
	 * Returns all rows from the observacion_item table that match the criteria 'lista_chequeo = :listaChequeo'.
	 */
	public ObservacionItem[] findWhereListaChequeoEquals(String listaChequeo) throws ObservacionItemDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE lista_chequeo = ? ORDER BY lista_chequeo", new Object[] { listaChequeo } );
	}

	/** 
	 * Returns all rows from the observacion_item table that match the criteria 'id_item = :idItem'.
	 */
	public ObservacionItem[] findWhereIdItemEquals(int idItem) throws ObservacionItemDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE id_item = ? ORDER BY id_item", new Object[] {  new Integer(idItem) } );
	}

	/** 
	 * Returns all rows from the observacion_item table that match the criteria 'observacion = :observacion'.
	 */
	public ObservacionItem[] findWhereObservacionEquals(String observacion) throws ObservacionItemDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE observacion = ? ORDER BY observacion", new Object[] { observacion } );
	}

	/** 
	 * Returns all rows from the observacion_item table that match the criteria 'jurados = :jurados'.
	 */
	public ObservacionItem[] findWhereJuradosEquals(String jurados) throws ObservacionItemDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE jurados = ? ORDER BY jurados", new Object[] { jurados } );
	}

	/** 
	 * Returns all rows from the observacion_item table that match the criteria 'fecha = :fecha'.
	 */
	public ObservacionItem[] findWhereFechaEquals(Date fecha) throws ObservacionItemDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE fecha = ? ORDER BY fecha", new Object[] { fecha==null ? null : new java.sql.Timestamp( fecha.getTime() ) } );
	}

	/** 
	 * Returns all rows from the observacion_item table that match the criteria 'usuario = :usuario'.
	 */
	public ObservacionItem[] findWhereUsuarioEquals(String usuario) throws ObservacionItemDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE usuario = ? ORDER BY usuario", new Object[] { usuario } );
	}

	/**
	 * Method 'ObservacionItemDaoImpl'
	 * 
	 */
	public ObservacionItemDaoImpl()
	{
	}

	/**
	 * Method 'ObservacionItemDaoImpl'
	 * 
	 * @param userConn
	 */
	public ObservacionItemDaoImpl(final Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "observador_de_proyectos.observacion_item";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected ObservacionItem fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			ObservacionItem dto = new ObservacionItem();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected ObservacionItem[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			ObservacionItem dto = new ObservacionItem();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		ObservacionItem ret[] = new ObservacionItem[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(ObservacionItem dto, ResultSet rs) throws SQLException
	{
		dto.setIdObservacion( rs.getInt( COLUMN_ID_OBSERVACION ) );
		dto.setNumeroFicha( rs.getString( COLUMN_NUMERO_FICHA ) );
		dto.setGrupoCodigo( rs.getInt( COLUMN_GRUPO_CODIGO ) );
		dto.setListaChequeo( rs.getString( COLUMN_LISTA_CHEQUEO ) );
		dto.setIdItem( rs.getInt( COLUMN_ID_ITEM ) );
		dto.setObservacion( rs.getString( COLUMN_OBSERVACION ) );
		dto.setJurados( rs.getString( COLUMN_JURADOS ) );
		dto.setFecha( rs.getTimestamp(COLUMN_FECHA ) );
		dto.setUsuario( rs.getString( COLUMN_USUARIO ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(ObservacionItem dto)
	{
	}

	/** 
	 * Returns all rows from the observacion_item table that match the specified arbitrary SQL statement
	 */
	public ObservacionItem[] findByDynamicSelect(String sql, Object[] sqlParams) throws ObservacionItemDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ObservacionItemDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the observacion_item table that match the specified arbitrary SQL statement
	 */
	public ObservacionItem[] findByDynamicWhere(String sql, Object[] sqlParams) throws ObservacionItemDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ObservacionItemDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
