/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controller.dao.jdbc;

import co.edu.sena.controller.dao.*;
import co.edu.sena.controller.factory.*;
import co.edu.sena.model.dao.dto.*;
import co.edu.sena.controller.dao.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class ProgramaDaoImpl extends AbstractDAO implements ProgramaDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT codigo_version, estado, nombre FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( codigo_version, estado, nombre ) VALUES ( ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET codigo_version = ?, estado = ?, nombre = ? WHERE codigo_version = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE codigo_version = ?";

	/** 
	 * Index of column codigo_version
	 */
	protected static final int COLUMN_CODIGO_VERSION = 1;

	/** 
	 * Index of column estado
	 */
	protected static final int COLUMN_ESTADO = 2;

	/** 
	 * Index of column nombre
	 */
	protected static final int COLUMN_NOMBRE = 3;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 3;

	/** 
	 * Index of primary-key column codigo_version
	 */
	protected static final int PK_COLUMN_CODIGO_VERSION = 1;

	/** 
	 * Inserts a new row in the programa table.
	 */
	public ProgramaPk insert(Programa dto) throws ProgramaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setString( index++, dto.getCodigoVersion() );
			stmt.setString( index++, dto.getEstado() );
			stmt.setString( index++, dto.getNombre() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ProgramaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the programa table.
	 */
	public void update(ProgramaPk pk, Programa dto) throws ProgramaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setString( index++, dto.getCodigoVersion() );
			stmt.setString( index++, dto.getEstado() );
			stmt.setString( index++, dto.getNombre() );
			stmt.setString( 4, pk.getCodigoVersion() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ProgramaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the programa table.
	 */
	public void delete(ProgramaPk pk) throws ProgramaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setString( 1, pk.getCodigoVersion() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ProgramaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the programa table that matches the specified primary-key value.
	 */
	public Programa findByPrimaryKey(ProgramaPk pk) throws ProgramaDaoException
	{
		return findByPrimaryKey( pk.getCodigoVersion() );
	}

	/** 
	 * Returns all rows from the programa table that match the criteria 'codigo_version = :codigoVersion'.
	 */
	public Programa findByPrimaryKey(String codigoVersion) throws ProgramaDaoException
	{
		Programa ret[] = findByDynamicSelect( SQL_SELECT + " WHERE codigo_version = ?", new Object[] { codigoVersion } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the programa table that match the criteria ''.
	 */
	public Programa[] findAll() throws ProgramaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY codigo_version", null );
	}

	/** 
	 * Returns all rows from the programa table that match the criteria 'codigo_version = :codigoVersion'.
	 */
	public Programa[] findWhereCodigoVersionEquals(String codigoVersion) throws ProgramaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE codigo_version = ? ORDER BY codigo_version", new Object[] { codigoVersion } );
	}

	/** 
	 * Returns all rows from the programa table that match the criteria 'estado = :estado'.
	 */
	public Programa[] findWhereEstadoEquals(String estado) throws ProgramaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE estado = ? ORDER BY estado", new Object[] { estado } );
	}

	/** 
	 * Returns all rows from the programa table that match the criteria 'nombre = :nombre'.
	 */
	public Programa[] findWhereNombreEquals(String nombre) throws ProgramaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE nombre = ? ORDER BY nombre", new Object[] { nombre } );
	}

	/**
	 * Method 'ProgramaDaoImpl'
	 * 
	 */
	public ProgramaDaoImpl()
	{
	}

	/**
	 * Method 'ProgramaDaoImpl'
	 * 
	 * @param userConn
	 */
	public ProgramaDaoImpl(final Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "observador_de_proyectos.programa";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Programa fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Programa dto = new Programa();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Programa[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Programa dto = new Programa();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Programa ret[] = new Programa[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Programa dto, ResultSet rs) throws SQLException
	{
		dto.setCodigoVersion( rs.getString( COLUMN_CODIGO_VERSION ) );
		dto.setEstado( rs.getString( COLUMN_ESTADO ) );
		dto.setNombre( rs.getString( COLUMN_NOMBRE ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Programa dto)
	{
	}

	/** 
	 * Returns all rows from the programa table that match the specified arbitrary SQL statement
	 */
	public Programa[] findByDynamicSelect(String sql, Object[] sqlParams) throws ProgramaDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ProgramaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the programa table that match the specified arbitrary SQL statement
	 */
	public Programa[] findByDynamicWhere(String sql, Object[] sqlParams) throws ProgramaDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ProgramaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
