/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controller.dao.jdbc;

import co.edu.sena.controller.dao.*;
import co.edu.sena.controller.factory.*;
import co.edu.sena.model.dao.dto.*;
import co.edu.sena.controller.dao.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class RaeHasTrimestreDaoImpl extends AbstractDAO implements RaeHasTrimestreDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT rae_codigo, competencia_codigo, programa_codigo_version, id_trimestre, jornada FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( rae_codigo, competencia_codigo, programa_codigo_version, id_trimestre, jornada ) VALUES ( ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET rae_codigo = ?, competencia_codigo = ?, programa_codigo_version = ?, id_trimestre = ?, jornada = ? WHERE rae_codigo = ? AND competencia_codigo = ? AND programa_codigo_version = ? AND id_trimestre = ? AND jornada = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE rae_codigo = ? AND competencia_codigo = ? AND programa_codigo_version = ? AND id_trimestre = ? AND jornada = ?";

	/** 
	 * Index of column rae_codigo
	 */
	protected static final int COLUMN_RAE_CODIGO = 1;

	/** 
	 * Index of column competencia_codigo
	 */
	protected static final int COLUMN_COMPETENCIA_CODIGO = 2;

	/** 
	 * Index of column programa_codigo_version
	 */
	protected static final int COLUMN_PROGRAMA_CODIGO_VERSION = 3;

	/** 
	 * Index of column id_trimestre
	 */
	protected static final int COLUMN_ID_TRIMESTRE = 4;

	/** 
	 * Index of column jornada
	 */
	protected static final int COLUMN_JORNADA = 5;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 5;

	/** 
	 * Index of primary-key column rae_codigo
	 */
	protected static final int PK_COLUMN_RAE_CODIGO = 1;

	/** 
	 * Index of primary-key column competencia_codigo
	 */
	protected static final int PK_COLUMN_COMPETENCIA_CODIGO = 2;

	/** 
	 * Index of primary-key column programa_codigo_version
	 */
	protected static final int PK_COLUMN_PROGRAMA_CODIGO_VERSION = 3;

	/** 
	 * Index of primary-key column id_trimestre
	 */
	protected static final int PK_COLUMN_ID_TRIMESTRE = 4;

	/** 
	 * Index of primary-key column jornada
	 */
	protected static final int PK_COLUMN_JORNADA = 5;

	/** 
	 * Inserts a new row in the rae_has_trimestre table.
	 */
	public RaeHasTrimestrePk insert(RaeHasTrimestre dto) throws RaeHasTrimestreDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setString( index++, dto.getRaeCodigo() );
			stmt.setString( index++, dto.getCompetenciaCodigo() );
			stmt.setString( index++, dto.getProgramaCodigoVersion() );
			stmt.setString( index++, dto.getIdTrimestre() );
			stmt.setString( index++, dto.getJornada() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new RaeHasTrimestreDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the rae_has_trimestre table.
	 */
	public void update(RaeHasTrimestrePk pk, RaeHasTrimestre dto) throws RaeHasTrimestreDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setString( index++, dto.getRaeCodigo() );
			stmt.setString( index++, dto.getCompetenciaCodigo() );
			stmt.setString( index++, dto.getProgramaCodigoVersion() );
			stmt.setString( index++, dto.getIdTrimestre() );
			stmt.setString( index++, dto.getJornada() );
			stmt.setString( 6, pk.getRaeCodigo() );
			stmt.setString( 7, pk.getCompetenciaCodigo() );
			stmt.setString( 8, pk.getProgramaCodigoVersion() );
			stmt.setString( 9, pk.getIdTrimestre() );
			stmt.setString( 10, pk.getJornada() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new RaeHasTrimestreDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the rae_has_trimestre table.
	 */
	public void delete(RaeHasTrimestrePk pk) throws RaeHasTrimestreDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setString( 1, pk.getRaeCodigo() );
			stmt.setString( 2, pk.getCompetenciaCodigo() );
			stmt.setString( 3, pk.getProgramaCodigoVersion() );
			stmt.setString( 4, pk.getIdTrimestre() );
			stmt.setString( 5, pk.getJornada() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new RaeHasTrimestreDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the rae_has_trimestre table that matches the specified primary-key value.
	 */
	public RaeHasTrimestre findByPrimaryKey(RaeHasTrimestrePk pk) throws RaeHasTrimestreDaoException
	{
		return findByPrimaryKey( pk.getRaeCodigo(), pk.getCompetenciaCodigo(), pk.getProgramaCodigoVersion(), pk.getIdTrimestre(), pk.getJornada() );
	}

	/** 
	 * Returns all rows from the rae_has_trimestre table that match the criteria 'rae_codigo = :raeCodigo AND competencia_codigo = :competenciaCodigo AND programa_codigo_version = :programaCodigoVersion AND id_trimestre = :idTrimestre AND jornada = :jornada'.
	 */
	public RaeHasTrimestre findByPrimaryKey(String raeCodigo, String competenciaCodigo, String programaCodigoVersion, String idTrimestre, String jornada) throws RaeHasTrimestreDaoException
	{
		RaeHasTrimestre ret[] = findByDynamicSelect( SQL_SELECT + " WHERE rae_codigo = ? AND competencia_codigo = ? AND programa_codigo_version = ? AND id_trimestre = ? AND jornada = ?", new Object[] { raeCodigo, competenciaCodigo, programaCodigoVersion, idTrimestre, jornada } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the rae_has_trimestre table that match the criteria ''.
	 */
	public RaeHasTrimestre[] findAll() throws RaeHasTrimestreDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY rae_codigo, competencia_codigo, programa_codigo_version, id_trimestre, jornada", null );
	}

	/** 
	 * Returns all rows from the rae_has_trimestre table that match the criteria 'rae_codigo = :raeCodigo AND competencia_codigo = :competenciaCodigo AND programa_codigo_version = :programaCodigoVersion'.
	 */
	public RaeHasTrimestre[] findByRae(String raeCodigo, String competenciaCodigo, String programaCodigoVersion) throws RaeHasTrimestreDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE rae_codigo = ? AND competencia_codigo = ? AND programa_codigo_version = ?", new Object[] { raeCodigo, competenciaCodigo, programaCodigoVersion } );
	}

	/** 
	 * Returns all rows from the rae_has_trimestre table that match the criteria 'id_trimestre = :idTrimestre AND jornada = :jornada'.
	 */
	public RaeHasTrimestre[] findByTrimestre(String idTrimestre, String jornada) throws RaeHasTrimestreDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE id_trimestre = ? AND jornada = ?", new Object[] { idTrimestre, jornada } );
	}

	/** 
	 * Returns all rows from the rae_has_trimestre table that match the criteria 'rae_codigo = :raeCodigo'.
	 */
	public RaeHasTrimestre[] findWhereRaeCodigoEquals(String raeCodigo) throws RaeHasTrimestreDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE rae_codigo = ? ORDER BY rae_codigo", new Object[] { raeCodigo } );
	}

	/** 
	 * Returns all rows from the rae_has_trimestre table that match the criteria 'competencia_codigo = :competenciaCodigo'.
	 */
	public RaeHasTrimestre[] findWhereCompetenciaCodigoEquals(String competenciaCodigo) throws RaeHasTrimestreDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE competencia_codigo = ? ORDER BY competencia_codigo", new Object[] { competenciaCodigo } );
	}

	/** 
	 * Returns all rows from the rae_has_trimestre table that match the criteria 'programa_codigo_version = :programaCodigoVersion'.
	 */
	public RaeHasTrimestre[] findWhereProgramaCodigoVersionEquals(String programaCodigoVersion) throws RaeHasTrimestreDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE programa_codigo_version = ? ORDER BY programa_codigo_version", new Object[] { programaCodigoVersion } );
	}

	/** 
	 * Returns all rows from the rae_has_trimestre table that match the criteria 'id_trimestre = :idTrimestre'.
	 */
	public RaeHasTrimestre[] findWhereIdTrimestreEquals(String idTrimestre) throws RaeHasTrimestreDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE id_trimestre = ? ORDER BY id_trimestre", new Object[] { idTrimestre } );
	}

	/** 
	 * Returns all rows from the rae_has_trimestre table that match the criteria 'jornada = :jornada'.
	 */
	public RaeHasTrimestre[] findWhereJornadaEquals(String jornada) throws RaeHasTrimestreDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE jornada = ? ORDER BY jornada", new Object[] { jornada } );
	}

	/**
	 * Method 'RaeHasTrimestreDaoImpl'
	 * 
	 */
	public RaeHasTrimestreDaoImpl()
	{
	}

	/**
	 * Method 'RaeHasTrimestreDaoImpl'
	 * 
	 * @param userConn
	 */
	public RaeHasTrimestreDaoImpl(final Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "observador_de_proyectos.rae_has_trimestre";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected RaeHasTrimestre fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			RaeHasTrimestre dto = new RaeHasTrimestre();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected RaeHasTrimestre[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			RaeHasTrimestre dto = new RaeHasTrimestre();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		RaeHasTrimestre ret[] = new RaeHasTrimestre[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(RaeHasTrimestre dto, ResultSet rs) throws SQLException
	{
		dto.setRaeCodigo( rs.getString( COLUMN_RAE_CODIGO ) );
		dto.setCompetenciaCodigo( rs.getString( COLUMN_COMPETENCIA_CODIGO ) );
		dto.setProgramaCodigoVersion( rs.getString( COLUMN_PROGRAMA_CODIGO_VERSION ) );
		dto.setIdTrimestre( rs.getString( COLUMN_ID_TRIMESTRE ) );
		dto.setJornada( rs.getString( COLUMN_JORNADA ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(RaeHasTrimestre dto)
	{
	}

	/** 
	 * Returns all rows from the rae_has_trimestre table that match the specified arbitrary SQL statement
	 */
	public RaeHasTrimestre[] findByDynamicSelect(String sql, Object[] sqlParams) throws RaeHasTrimestreDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new RaeHasTrimestreDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the rae_has_trimestre table that match the specified arbitrary SQL statement
	 */
	public RaeHasTrimestre[] findByDynamicWhere(String sql, Object[] sqlParams) throws RaeHasTrimestreDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new RaeHasTrimestreDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
