/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controller.dao;

import co.edu.sena.model.dao.dto.*;
import co.edu.sena.controller.dao.exceptions.*;

public interface FichaHasListaDao
{
	/** 
	 * Inserts a new row in the ficha_has_lista table.
	 */
	public FichaHasListaPk insert(FichaHasLista dto) throws FichaHasListaDaoException;

	/** 
	 * Updates a single row in the ficha_has_lista table.
	 */
	public void update(FichaHasListaPk pk, FichaHasLista dto) throws FichaHasListaDaoException;

	/** 
	 * Deletes a single row in the ficha_has_lista table.
	 */
	public void delete(FichaHasListaPk pk) throws FichaHasListaDaoException;

	/** 
	 * Returns the rows from the ficha_has_lista table that matches the specified primary-key value.
	 */
	public FichaHasLista findByPrimaryKey(FichaHasListaPk pk) throws FichaHasListaDaoException;

	/** 
	 * Returns all rows from the ficha_has_lista table that match the criteria 'ficha = :ficha'.
	 */
	public FichaHasLista findByPrimaryKey(String ficha) throws FichaHasListaDaoException;

	/** 
	 * Returns all rows from the ficha_has_lista table that match the criteria ''.
	 */
	public FichaHasLista[] findAll() throws FichaHasListaDaoException;

	/** 
	 * Returns all rows from the ficha_has_lista table that match the criteria 'ficha = :ficha'.
	 */
	public FichaHasLista[] findByFicha(String ficha) throws FichaHasListaDaoException;

	/** 
	 * Returns all rows from the ficha_has_lista table that match the criteria 'lista_chequeo = :listaChequeo'.
	 */
	public FichaHasLista[] findByListaChequeo(String listaChequeo) throws FichaHasListaDaoException;

	/** 
	 * Returns all rows from the ficha_has_lista table that match the criteria 'ficha = :ficha'.
	 */
	public FichaHasLista[] findWhereFichaEquals(String ficha) throws FichaHasListaDaoException;

	/** 
	 * Returns all rows from the ficha_has_lista table that match the criteria 'lista_chequeo = :listaChequeo'.
	 */
	public FichaHasLista[] findWhereListaChequeoEquals(String listaChequeo) throws FichaHasListaDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the ficha_has_lista table that match the specified arbitrary SQL statement
	 */
	public FichaHasLista[] findByDynamicSelect(String sql, Object[] sqlParams) throws FichaHasListaDaoException;

	/** 
	 * Returns all rows from the ficha_has_lista table that match the specified arbitrary SQL statement
	 */
	public FichaHasLista[] findByDynamicWhere(String sql, Object[] sqlParams) throws FichaHasListaDaoException;

}
