/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controller.dao;

import co.edu.sena.model.dao.dto.*;
import co.edu.sena.controller.dao.exceptions.*;

public interface ProgramaDao
{
	/** 
	 * Inserts a new row in the programa table.
	 */
	public ProgramaPk insert(Programa dto) throws ProgramaDaoException;

	/** 
	 * Updates a single row in the programa table.
	 */
	public void update(ProgramaPk pk, Programa dto) throws ProgramaDaoException;

	/** 
	 * Deletes a single row in the programa table.
	 */
	public void delete(ProgramaPk pk) throws ProgramaDaoException;

	/** 
	 * Returns the rows from the programa table that matches the specified primary-key value.
	 */
	public Programa findByPrimaryKey(ProgramaPk pk) throws ProgramaDaoException;

	/** 
	 * Returns all rows from the programa table that match the criteria 'codigo_version = :codigoVersion'.
	 */
	public Programa findByPrimaryKey(String codigoVersion) throws ProgramaDaoException;

	/** 
	 * Returns all rows from the programa table that match the criteria ''.
	 */
	public Programa[] findAll() throws ProgramaDaoException;

	/** 
	 * Returns all rows from the programa table that match the criteria 'codigo_version = :codigoVersion'.
	 */
	public Programa[] findWhereCodigoVersionEquals(String codigoVersion) throws ProgramaDaoException;

	/** 
	 * Returns all rows from the programa table that match the criteria 'estado = :estado'.
	 */
	public Programa[] findWhereEstadoEquals(String estado) throws ProgramaDaoException;

	/** 
	 * Returns all rows from the programa table that match the criteria 'nombre = :nombre'.
	 */
	public Programa[] findWhereNombreEquals(String nombre) throws ProgramaDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the programa table that match the specified arbitrary SQL statement
	 */
	public Programa[] findByDynamicSelect(String sql, Object[] sqlParams) throws ProgramaDaoException;

	/** 
	 * Returns all rows from the programa table that match the specified arbitrary SQL statement
	 */
	public Programa[] findByDynamicWhere(String sql, Object[] sqlParams) throws ProgramaDaoException;

}
