/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controller.dao;

import co.edu.sena.model.dao.dto.*;
import co.edu.sena.controller.dao.exceptions.*;

public interface TipoInstructorDao
{
	/** 
	 * Inserts a new row in the tipo_instructor table.
	 */
	public TipoInstructorPk insert(TipoInstructor dto) throws TipoInstructorDaoException;

	/** 
	 * Updates a single row in the tipo_instructor table.
	 */
	public void update(TipoInstructorPk pk, TipoInstructor dto) throws TipoInstructorDaoException;

	/** 
	 * Deletes a single row in the tipo_instructor table.
	 */
	public void delete(TipoInstructorPk pk) throws TipoInstructorDaoException;

	/** 
	 * Returns the rows from the tipo_instructor table that matches the specified primary-key value.
	 */
	public TipoInstructor findByPrimaryKey(TipoInstructorPk pk) throws TipoInstructorDaoException;

	/** 
	 * Returns all rows from the tipo_instructor table that match the criteria 'modalidad = :modalidad'.
	 */
	public TipoInstructor findByPrimaryKey(String modalidad) throws TipoInstructorDaoException;

	/** 
	 * Returns all rows from the tipo_instructor table that match the criteria ''.
	 */
	public TipoInstructor[] findAll() throws TipoInstructorDaoException;

	/** 
	 * Returns all rows from the tipo_instructor table that match the criteria 'modalidad = :modalidad'.
	 */
	public TipoInstructor[] findWhereModalidadEquals(String modalidad) throws TipoInstructorDaoException;

	/** 
	 * Returns all rows from the tipo_instructor table that match the criteria 'estado = :estado'.
	 */
	public TipoInstructor[] findWhereEstadoEquals(short estado) throws TipoInstructorDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the tipo_instructor table that match the specified arbitrary SQL statement
	 */
	public TipoInstructor[] findByDynamicSelect(String sql, Object[] sqlParams) throws TipoInstructorDaoException;

	/** 
	 * Returns all rows from the tipo_instructor table that match the specified arbitrary SQL statement
	 */
	public TipoInstructor[] findByDynamicWhere(String sql, Object[] sqlParams) throws TipoInstructorDaoException;

}
