/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controller.factory;

import java.sql.Connection;
import co.edu.sena.controller.dao.*;
import co.edu.sena.controller.dao.jdbc.*;

public class TipoInstructorDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return TipoInstructorDao
	 */
	public static TipoInstructorDao create()
	{
		return new TipoInstructorDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return TipoInstructorDao
	 */
	public static TipoInstructorDao create(Connection conn)
	{
		return new TipoInstructorDaoImpl( conn );
	}

}
