/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controller.factory;

import java.sql.Connection;
import co.edu.sena.controller.dao.*;
import co.edu.sena.controller.dao.jdbc.*;

public class UsuarioDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return UsuarioDao
	 */
	public static UsuarioDao create()
	{
		return new UsuarioDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return UsuarioDao
	 */
	public static UsuarioDao create(Connection conn)
	{
		return new UsuarioDaoImpl( conn );
	}

}
