/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.pruebas;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import co.edu.sena.controller.dao.FichaHasListaDao;
import co.edu.sena.model.dao.dto.FichaHasLista;
import co.edu.sena.controller.dao.exceptions.FichaHasListaDaoException;
import co.edu.sena.controller.factory.FichaHasListaDaoFactory;

public class FichaHasListaDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByFicha("");
		// findByListaChequeo("");
		// findWhereFichaEquals("");
		// findWhereListaChequeoEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			FichaHasListaDao _dao = getFichaHasListaDao();
			FichaHasLista _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByFicha'
	 * 
	 * @param ficha
	 */
	public static void findByFicha(String ficha)
	{
		try {
			FichaHasListaDao _dao = getFichaHasListaDao();
			FichaHasLista _result[] = _dao.findByFicha(ficha);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByListaChequeo'
	 * 
	 * @param listaChequeo
	 */
	public static void findByListaChequeo(String listaChequeo)
	{
		try {
			FichaHasListaDao _dao = getFichaHasListaDao();
			FichaHasLista _result[] = _dao.findByListaChequeo(listaChequeo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereFichaEquals'
	 * 
	 * @param ficha
	 */
	public static void findWhereFichaEquals(String ficha)
	{
		try {
			FichaHasListaDao _dao = getFichaHasListaDao();
			FichaHasLista _result[] = _dao.findWhereFichaEquals(ficha);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereListaChequeoEquals'
	 * 
	 * @param listaChequeo
	 */
	public static void findWhereListaChequeoEquals(String listaChequeo)
	{
		try {
			FichaHasListaDao _dao = getFichaHasListaDao();
			FichaHasLista _result[] = _dao.findWhereListaChequeoEquals(listaChequeo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getFichaHasListaDao'
	 * 
	 * @return FichaHasListaDao
	 */
	public static FichaHasListaDao getFichaHasListaDao()
	{
		return FichaHasListaDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(FichaHasLista dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getFicha() );
		buf.append( ", " );
		buf.append( dto.getListaChequeo() );
		System.out.println( buf.toString() );
	}

}
