/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.pruebas;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import co.edu.sena.controller.dao.GrupoProyectoDao;
import co.edu.sena.model.dao.dto.GrupoProyecto;
import co.edu.sena.controller.dao.exceptions.GrupoProyectoDaoException;
import co.edu.sena.controller.factory.GrupoProyectoDaoFactory;

public class GrupoProyectoDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByFicha("");
		// findWhereNumeroFichaEquals("");
		// findWhereCodigoEquals(0);
		// findWhereNombreProyectoEquals("");
		// findWhereEstadoGrupoEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			GrupoProyectoDao _dao = getGrupoProyectoDao();
			GrupoProyecto _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByFicha'
	 * 
	 * @param numeroFicha
	 */
	public static void findByFicha(String numeroFicha)
	{
		try {
			GrupoProyectoDao _dao = getGrupoProyectoDao();
			GrupoProyecto _result[] = _dao.findByFicha(numeroFicha);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNumeroFichaEquals'
	 * 
	 * @param numeroFicha
	 */
	public static void findWhereNumeroFichaEquals(String numeroFicha)
	{
		try {
			GrupoProyectoDao _dao = getGrupoProyectoDao();
			GrupoProyecto _result[] = _dao.findWhereNumeroFichaEquals(numeroFicha);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCodigoEquals'
	 * 
	 * @param codigo
	 */
	public static void findWhereCodigoEquals(int codigo)
	{
		try {
			GrupoProyectoDao _dao = getGrupoProyectoDao();
			GrupoProyecto _result[] = _dao.findWhereCodigoEquals(codigo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNombreProyectoEquals'
	 * 
	 * @param nombreProyecto
	 */
	public static void findWhereNombreProyectoEquals(String nombreProyecto)
	{
		try {
			GrupoProyectoDao _dao = getGrupoProyectoDao();
			GrupoProyecto _result[] = _dao.findWhereNombreProyectoEquals(nombreProyecto);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEstadoGrupoEquals'
	 * 
	 * @param estadoGrupo
	 */
	public static void findWhereEstadoGrupoEquals(String estadoGrupo)
	{
		try {
			GrupoProyectoDao _dao = getGrupoProyectoDao();
			GrupoProyecto _result[] = _dao.findWhereEstadoGrupoEquals(estadoGrupo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getGrupoProyectoDao'
	 * 
	 * @return GrupoProyectoDao
	 */
	public static GrupoProyectoDao getGrupoProyectoDao()
	{
		return GrupoProyectoDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(GrupoProyecto dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getNumeroFicha() );
		buf.append( ", " );
		buf.append( dto.getCodigo() );
		buf.append( ", " );
		buf.append( dto.getNombreProyecto() );
		buf.append( ", " );
		buf.append( dto.getEstadoGrupo() );
		System.out.println( buf.toString() );
	}

}
