/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.pruebas;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import co.edu.sena.controller.dao.ListaChequeoDao;
import co.edu.sena.model.dao.dto.ListaChequeo;
import co.edu.sena.controller.dao.exceptions.ListaChequeoDaoException;
import co.edu.sena.controller.factory.ListaChequeoDaoFactory;

public class ListaChequeoDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByPrograma("");
		// findWhereIdListaEquals("");
		// findWhereEstadoEquals(0);
		// findWhereProgramaCodigoVersionEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			ListaChequeoDao _dao = getListaChequeoDao();
			ListaChequeo _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByPrograma'
	 * 
	 * @param programaCodigoVersion
	 */
	public static void findByPrograma(String programaCodigoVersion)
	{
		try {
			ListaChequeoDao _dao = getListaChequeoDao();
			ListaChequeo _result[] = _dao.findByPrograma(programaCodigoVersion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdListaEquals'
	 * 
	 * @param idLista
	 */
	public static void findWhereIdListaEquals(String idLista)
	{
		try {
			ListaChequeoDao _dao = getListaChequeoDao();
			ListaChequeo _result[] = _dao.findWhereIdListaEquals(idLista);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEstadoEquals'
	 * 
	 * @param estado
	 */
	public static void findWhereEstadoEquals(short estado)
	{
		try {
			ListaChequeoDao _dao = getListaChequeoDao();
			ListaChequeo _result[] = _dao.findWhereEstadoEquals(estado);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereProgramaCodigoVersionEquals'
	 * 
	 * @param programaCodigoVersion
	 */
	public static void findWhereProgramaCodigoVersionEquals(String programaCodigoVersion)
	{
		try {
			ListaChequeoDao _dao = getListaChequeoDao();
			ListaChequeo _result[] = _dao.findWhereProgramaCodigoVersionEquals(programaCodigoVersion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getListaChequeoDao'
	 * 
	 * @return ListaChequeoDao
	 */
	public static ListaChequeoDao getListaChequeoDao()
	{
		return ListaChequeoDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(ListaChequeo dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdLista() );
		buf.append( ", " );
		buf.append( dto.getEstado() );
		buf.append( ", " );
		buf.append( dto.getProgramaCodigoVersion() );
		System.out.println( buf.toString() );
	}

}
