/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.pruebas;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import co.edu.sena.controller.dao.ObservacionGeneralDao;
import co.edu.sena.model.dao.dto.ObservacionGeneral;
import co.edu.sena.controller.dao.exceptions.ObservacionGeneralDaoException;
import co.edu.sena.controller.factory.ObservacionGeneralDaoFactory;

public class ObservacionGeneralDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByGrupoProyecto("", 0);
		// findWhereGrupoNumeroFichaEquals("");
		// findWhereGrupoCodigoEquals(0);
		// findWhereIdObservacionEquals(0);
		// findWhereObservacionEquals("");
		// findWhereJuradoEquals("");
		// findWhereFechaEquals(null);
		// findWhereUsuarioEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			ObservacionGeneralDao _dao = getObservacionGeneralDao();
			ObservacionGeneral _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByGrupoProyecto'
	 * 
	 * @param grupoNumeroFicha
	 * @param grupoCodigo
	 */
	public static void findByGrupoProyecto(String grupoNumeroFicha, int grupoCodigo)
	{
		try {
			ObservacionGeneralDao _dao = getObservacionGeneralDao();
			ObservacionGeneral _result[] = _dao.findByGrupoProyecto(grupoNumeroFicha, grupoCodigo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereGrupoNumeroFichaEquals'
	 * 
	 * @param grupoNumeroFicha
	 */
	public static void findWhereGrupoNumeroFichaEquals(String grupoNumeroFicha)
	{
		try {
			ObservacionGeneralDao _dao = getObservacionGeneralDao();
			ObservacionGeneral _result[] = _dao.findWhereGrupoNumeroFichaEquals(grupoNumeroFicha);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereGrupoCodigoEquals'
	 * 
	 * @param grupoCodigo
	 */
	public static void findWhereGrupoCodigoEquals(int grupoCodigo)
	{
		try {
			ObservacionGeneralDao _dao = getObservacionGeneralDao();
			ObservacionGeneral _result[] = _dao.findWhereGrupoCodigoEquals(grupoCodigo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdObservacionEquals'
	 * 
	 * @param idObservacion
	 */
	public static void findWhereIdObservacionEquals(int idObservacion)
	{
		try {
			ObservacionGeneralDao _dao = getObservacionGeneralDao();
			ObservacionGeneral _result[] = _dao.findWhereIdObservacionEquals(idObservacion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereObservacionEquals'
	 * 
	 * @param observacion
	 */
	public static void findWhereObservacionEquals(String observacion)
	{
		try {
			ObservacionGeneralDao _dao = getObservacionGeneralDao();
			ObservacionGeneral _result[] = _dao.findWhereObservacionEquals(observacion);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereJuradoEquals'
	 * 
	 * @param jurado
	 */
	public static void findWhereJuradoEquals(String jurado)
	{
		try {
			ObservacionGeneralDao _dao = getObservacionGeneralDao();
			ObservacionGeneral _result[] = _dao.findWhereJuradoEquals(jurado);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereFechaEquals'
	 * 
	 * @param fecha
	 */
	public static void findWhereFechaEquals(Date fecha)
	{
		try {
			ObservacionGeneralDao _dao = getObservacionGeneralDao();
			ObservacionGeneral _result[] = _dao.findWhereFechaEquals(fecha);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUsuarioEquals'
	 * 
	 * @param usuario
	 */
	public static void findWhereUsuarioEquals(String usuario)
	{
		try {
			ObservacionGeneralDao _dao = getObservacionGeneralDao();
			ObservacionGeneral _result[] = _dao.findWhereUsuarioEquals(usuario);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getObservacionGeneralDao'
	 * 
	 * @return ObservacionGeneralDao
	 */
	public static ObservacionGeneralDao getObservacionGeneralDao()
	{
		return ObservacionGeneralDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(ObservacionGeneral dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getGrupoNumeroFicha() );
		buf.append( ", " );
		buf.append( dto.getGrupoCodigo() );
		buf.append( ", " );
		buf.append( dto.getIdObservacion() );
		buf.append( ", " );
		buf.append( dto.getObservacion() );
		buf.append( ", " );
		buf.append( dto.getJurado() );
		buf.append( ", " );
		buf.append( dto.getFecha() );
		buf.append( ", " );
		buf.append( dto.getUsuario() );
		System.out.println( buf.toString() );
	}

}
