/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.pruebas;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import co.edu.sena.controller.dao.TrimestreDao;
import co.edu.sena.model.dao.dto.Trimestre;
import co.edu.sena.controller.dao.exceptions.TrimestreDaoException;
import co.edu.sena.controller.factory.TrimestreDaoFactory;

public class TrimestreDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByJornada("");
		// findWhereIdTrimestreEquals("");
		// findWhereJornadaNombreEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			TrimestreDao _dao = getTrimestreDao();
			Trimestre _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByJornada'
	 * 
	 * @param jornadaNombre
	 */
	public static void findByJornada(String jornadaNombre)
	{
		try {
			TrimestreDao _dao = getTrimestreDao();
			Trimestre _result[] = _dao.findByJornada(jornadaNombre);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdTrimestreEquals'
	 * 
	 * @param idTrimestre
	 */
	public static void findWhereIdTrimestreEquals(String idTrimestre)
	{
		try {
			TrimestreDao _dao = getTrimestreDao();
			Trimestre _result[] = _dao.findWhereIdTrimestreEquals(idTrimestre);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereJornadaNombreEquals'
	 * 
	 * @param jornadaNombre
	 */
	public static void findWhereJornadaNombreEquals(String jornadaNombre)
	{
		try {
			TrimestreDao _dao = getTrimestreDao();
			Trimestre _result[] = _dao.findWhereJornadaNombreEquals(jornadaNombre);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getTrimestreDao'
	 * 
	 * @return TrimestreDao
	 */
	public static TrimestreDao getTrimestreDao()
	{
		return TrimestreDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Trimestre dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdTrimestre() );
		buf.append( ", " );
		buf.append( dto.getJornadaNombre() );
		System.out.println( buf.toString() );
	}

}
