/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.pruebas;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import co.edu.sena.controller.dao.ValoracionDao;
import co.edu.sena.model.dao.dto.Valoracion;
import co.edu.sena.controller.dao.exceptions.ValoracionDaoException;
import co.edu.sena.controller.factory.ValoracionDaoFactory;

public class ValoracionDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		 findAll();
		// findWhereValorEquals("");
		// findWhereEstadoEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			ValoracionDao _dao = getValoracionDao();
			Valoracion _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereValorEquals'
	 * 
	 * @param valor
	 */
	public static void findWhereValorEquals(String valor)
	{
		try {
			ValoracionDao _dao = getValoracionDao();
			Valoracion _result[] = _dao.findWhereValorEquals(valor);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEstadoEquals'
	 * 
	 * @param estado
	 */
	public static void findWhereEstadoEquals(short estado)
	{
		try {
			ValoracionDao _dao = getValoracionDao();
			Valoracion _result[] = _dao.findWhereEstadoEquals(estado);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getValoracionDao'
	 * 
	 * @return ValoracionDao
	 */
	public static ValoracionDao getValoracionDao()
	{
		return ValoracionDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Valoracion dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getValor() );
		buf.append( ", " );
		buf.append( dto.getEstado() );
		System.out.println( buf.toString() );
	}

}
