/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package co.edu.sena.controller.dao.exceptions;

public class JornadaDaoException extends DaoException
{
	/**
	 * Method 'JornadaDaoException'
	 * 
	 * @param message
	 */
	public JornadaDaoException(String message)
	{
		super(message);
	}

	/**
	 * Method 'JornadaDaoException'
	 * 
	 * @param message
	 * @param cause
	 */
	public JornadaDaoException(String message, Throwable cause)
	{
		super(message, cause);
	}

}
